### ISSUE TITLE
[Broken] USANetwork now responds with "Unsupported URL"

### ISSUE THREAD

**Issue by mindofmicah** [blackjack4494/yt-dlc#105]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc --write-info-json --ap-mso=DTV --ap-username=USERNAME --ap-password=PASSWORD --verbose -i --no-cache-dir https://www.usanetwork.com/wwe-raw/video/raw-101220/4245138
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--write-info-json', u'--ap-mso=DTV', u'--ap-username=PRIVATE', u'--ap-password=PRIVATE', u'--verbose', u'-i', u'--no-cache-dir', u'https://www.usanetwork.com/wwe-raw/video/raw-101220/4245138']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.31
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-512010201020-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 4245138: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 4245138: Downloading webpage
[generic] 4245138: Extracting information
ERROR: Unsupported URL: https://www.usanetwork.com/wwe-raw/video/raw-101220/4245138
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/generic.py", line 2387, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dlc/youtube_dlc/compat.py", line 2562, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dlc/youtube_dlc/compat.py", line 2551, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 5, column 303
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.usanetwork.com/wwe-raw/video/raw-101220/4245138

```

## Description

Recently USANetwork.com had a redesign and now uses are new url structure for shows (I haven't dug into movies)
The regular expression in the existing extractor looks for **/videos/**, but the new structure uses **/video/**
https://github.com/blackjack4494/yt-dlc/blob/master/youtube_dlc/extractor/usanetwork.py#L13

https://www.usanetwork.com/wwe-raw/video/raw-101220/4245138 is the URL I'm using to test and it works fine if I am logged in with my DirectTv/Cable account.

**Comment by StevenDTX** [comment]
Switch to https://www.nbc.com/networks/usa

All the same videos are there and that works.

**Comment by mindofmicah** [comment]
@StevenDTX , thank you for this solution. I was able to update my workflow to use the NBC approach :)
