### ISSUE TITLE
[Broken] Downloading cwtv.com's videos no longer work.

### ISSUE THREAD

**Issue by antdude** [blackjack4494/yt-dlc#115]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
$ youtube-dlc -v https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.7.9 (CPython) - Linux-5.5.11-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[generic] the-13-scariest-movies-of-all-time: Requesting header
WARNING: Falling back on generic information extractor.
[generic] the-13-scariest-movies-of-all-time: Downloading webpage
[generic] the-13-scariest-movies-of-all-time: Extracting information
ERROR: Unsupported URL: https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/ant/bin/youtube-dlc/youtube_dlc/extractor/generic.py", line 3382, in _real_extract
    raise UnsupportedError(url)
youtube_dlc.utils.UnsupportedError: Unsupported URL: https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/

## Description

WRITE DESCRIPTION HERE
Downloading cwtv.com's videos no longer work. It now says "ERROR: Unsupported URL: ..." https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/ as an example.

Original youtube-dl v2020.11.01.1 doesn't work either. Thank you for reading and hopefully fixing it soon. :)

**Comment by october262** [comment]
use the Firefox addon called the stream detector
to grab the m3u8 files. just set it for youtube-dlc in the drop down box,
click copy all visible URLs and paste into the terminal to download.

**Comment by antdude** [comment]
Thanks. So, youtube-dl(c) can't do this inside?

**Comment by 2ShedsJackson** [comment]
It's not broken at all. The correct link address is
https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/?play=9545ce79-7f9c-44e4-9d42-f92340c5dc15
not just
https://www.cwtv.com/shows/more-video/the-13-scariest-movies-of-all-time/

**Comment by antdude** [comment]
Ah, thanks! :)
