### ISSUE TITLE
[Question] youtube-dlc -U doesn't work?

### ISSUE THREAD

**Issue by antdude** [blackjack4494/yt-dlc#133]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it me or is updating youtube-dlc with its -U parameter not working? Debug logs:

$  youtube-dlc -U -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.7.9 (CPython) - Linux-5.5.11-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
Current Build Hash ed08c4349d774db771d6198926c8053a0e1cfd0cd5bc7d6d87b1eabeaa3d331e
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dlc/youtube_dlc/update.py", line 62, in update_self
    newversion = opener.open(VERSION_URL).read().decode('utf-8').strip()
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

ERROR: can't find the current version. Please try again later.
Visit https://github.com/blackjack4494/yt-dlc/releases/latest
[ant@beta Downloads]$  youtube-dl -U -
^CTraceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ant/bin/youtube-dl/__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/extractors.py", line 1152, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/tinypic.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
KeyboardInterrupt

Thank you for reading and hopefully answering soon. :)

**Comment by michaelpoersch** [comment]
See main page: "DO NOT UPDATE using -U! ..."

**Comment by antdude** [comment]
Oh oops. Thanks!
