### ISSUE TITLE
VIU Extractor gettin a KeyError 

### ISSUE THREAD

**Issue by lopisode** [blackjack4494/yt-dlc#136]
PS C:\Users\13606> youtube-dlc --version
2020.11.07

I believe its the _download_json not returning 'data' but not sure how to fix this. 

PS C:\Users\13606> youtube-dlc https://www.viu.com/ott/sg/en-us/vod/307484/Men-on-a-Mission-Knowing-Brothers-2020 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.viu.com/ott/sg/en-us/vod/307484/Men-on-a-Mission-Knowing-Brothers-2020', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dlc version 2020.11.07
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-06-20-29ea4e1, ffprobe git-2020-06-20-29ea4e1
[debug] Proxy map: {}
[viu:ott] 307484: Downloading video info
[viu:ott] 307484: Downloading stream info
ERROR: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'
Traceback (most recent call last):
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dlc.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

**Comment by zackmark29** [comment]
I think @blackjack4494 already have fixed for that error.
I tried your link with my tool and there's no error

![1](https://user-images.githubusercontent.com/62680932/98804712-76dbcf80-2451-11eb-8694-250aebef9124.png)

**Comment by lopisode** [comment]
Is there something I am doing wrong? I just tried it again and got the same error. I upgraded to the latest release.

PS C:\Users\13606> youtube-dlc --version
 2020.11.11-3

PS C:\Users\13606> youtube-dlc https://www.viu.com/ott/sg/en-us/vod/307484/Men-on-a-Mission-Knowing-Brothers-2020 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.viu.com/ott/sg/en-us/vod/307484/Men-on-a-Mission-Knowing-Brothers-2020', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg git-2020-06-20-29ea4e1, ffprobe git-2020-06-20-29ea4e1
[debug] Proxy map: {}
[viu:ott] 307484: Downloading video info
[viu:ott] 307484: Downloading stream info
ERROR: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'
Traceback (most recent call last):
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\viu.py", line 226, in _real_extract
    stream_data = self._download_json(
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\13606\appdata\local\programs\python\python38-32\lib\site-packages\youtube_dlc\extractor\common.py", line 545, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dlc.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('data')); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
