### ISSUE TITLE
[Bug] YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/yt-dlc#145]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dlc version **2020.10.31**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Description

Take this as an example https://www.youtube.com/watch?v=sv_2LzgoB0

No error message will be logged because there is no html tag with unavailable message.  
However there is `playabilityStatus` in `ytInitialData` which tells some information.

**Comment by someziggyman** [comment]
I could be wrong, but this video ID seems truncated. It's not even playable in browser..
Also, I've tried it with the last available update of the original ytdl and the error message confirms this:

_-v -F https://www.youtube.com/watch?v=sv_2LzgoB0
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'https://www.youtube.com/watch?v=sv_2LzgoB0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.11.01.1
[debug] Python version 3.9.0 (CPython) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Incomplete YouTube ID sv_2LzgoB0. URL https://www.youtube.com/watch?v=sv_2LzgoB0 looks truncated.
Traceback (most recent call last):
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/youtube-dl/2020.11.1.1/libexec/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 3487, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: Incomplete YouTube ID sv_2LzgoB0. URL https://www.youtube.com/watch?v=sv_2LzgoB0 looks truncated._

**Comment by nicolaasjan** [comment]
YouTube said:

> Video not found

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/pull/27081
