### ISSUE TITLE
[Broken] Facebook Watch videos

### ISSUE THREAD

**Issue by 2ShedsJackson** [blackjack4494/yt-dlc#154]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.facebook.com/141043411701/videos/295690631678897']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.07
[debug] Python version 3.8.2 (CPython) - FreeBSD-12.0-RELEASE-p3-amd64-64bit-ELF
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 295690631678897: Downloading webpage
[facebook] 295690631678897: Downloading webpage
[facebook] 295690631678897: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/python3.8/site-packages/youtube_dlc/extractor/facebook.py", line 482, in _real_extract
    _, info_dict = self._extract_from_url(
  File "/usr/local/bin/python3.8/site-packages/youtube_dlc/extractor/facebook.py", line 380, in _extract_from_url
    raise ExtractorError('Cannot parse data')
youtube_dlc.utils.ExtractorError: Cannot parse data; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

youtube-dlc doesn't download Facebook Watch videos (movies, TV shows, music videos). It still works on most other Facebook videos. The video in the example is playable without logging in.

**Comment by october262** [comment]
try like this >  youtube-dlc --force-generic-extractor https://www.facebook.com/141043411701/videos/295690631678897

**Comment by 2ShedsJackson** [comment]
> try like this > youtube-dlc --force-generic-extractor https://www.facebook.com/141043411701/videos/295690631678897

Thanks. Any tips for a video like https://www.facebook.com/lionsgate/videos/974855332998732 ?  That video has a "custom" audience rather than a public one, requiring login.  I tried passing cookies but got back

[redirect] Following redirect to https://www.facebook.com/watch/?v=974855332998732
...
ERROR: Unsupported URL: https://www.facebook.com/watch/?v=974855332998732

**Comment by october262** [comment]
this link - https://www.facebook.com/lionsgate/videos/974855332998732
says it's expired. download may not be possible as it may be protected with DRM.

**Comment by 2ShedsJackson** [comment]
> says it's expired. download may not be possible as it may be protected with DRM.

It's definitely not expired. I see webm and audio mp4 fragments but haven't found a manifest file.

**Comment by october262** [comment]
> 
> 
> > says it's expired. download may not be possible as it may be protected with DRM.
> 
> It's definitely not expired. I see webm and audio mp4 fragments but haven't found a manifest file.

you might try the firefox addon called the stream detector or videodownload helper addon 
did get a hit with the stream detector addon but no link showed.
