### ISSUE TITLE
[Bug] KeyError: 'http_headers' when download YouTube subtitles with aria2c

### ISSUE THREAD

**Issue by awei78** [blackjack4494/yt-dlc#157]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Connected to pydev debugger (build 192.7142.56)
[youtube] 6Af6b_wyiwI: Downloading webpage
[youtube] Downloading just video 6Af6b_wyiwI because of --no-playlist
[youtube] 6Af6b_wyiwI: Looking for automatic captions
WARNING: Couldn't find automatic captions for 6Af6b_wyiwI
[info] Writing video subtitles to: The next outbreak We’re not ready _ Bill Gates-6Af6b_wyiwI.en.vtt
[download] Destination: The next outbreak We’re not ready _ Bill Gates-6Af6b_wyiwI.en.vtt
Traceback (most recent call last):
  File "E:\GitHub\youtube-dlc\youtube_dlc\__init__.py", line 487, in main
    _real_main(argv)
  File "E:\GitHub\youtube-dlc\youtube_dlc\__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "E:\GitHub\youtube-dlc\youtube_dlc\YoutubeDL.py", line 2104, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "E:\GitHub\youtube-dlc\youtube_dlc\YoutubeDL.py", line 846, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "E:\GitHub\youtube-dlc\youtube_dlc\YoutubeDL.py", line 901, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "E:\GitHub\youtube-dlc\youtube_dlc\YoutubeDL.py", line 1696, in process_video_result
    self.process_info(new_info)
  File "E:\GitHub\youtube-dlc\youtube_dlc\YoutubeDL.py", line 1894, in process_info
    dl(sub_filename, sub_info, subtitle=True)
  File "E:\GitHub\youtube-dlc\youtube_dlc\YoutubeDL.py", line 1866, in dl
    return fd.download(name, info, subtitle)
  File "E:\GitHub\youtube-dlc\youtube_dlc\downloader\common.py", line 373, in download
    return self.real_download(filename, info_dict)
  File "E:\GitHub\youtube-dlc\youtube_dlc\downloader\external.py", line 35, in real_download
    retval = self._call_downloader(tmpfilename, info_dict)
  File "E:\GitHub\youtube-dlc\youtube_dlc\downloader\external.py", line 101, in _call_downloader
    cmd = [encodeArgument(a) for a in self._make_cmd(tmpfilename, info_dict)]
  File "E:\GitHub\youtube-dlc\youtube_dlc\downloader\external.py", line 192, in _make_cmd
    for key, val in info_dict['http_headers'].items():
KeyError: 'http_headers'
```

## Description

When I download YouTube subtitles with aria2c, command like:

>`youtube-dlc --write-sub --sub-format "ass/srt/best" --write-auto-sub "https://www.youtube.com/watch?v=6Af6b_wyiwI" --external-downloader aria2c --external-downloader-args "-x 16 -k 1M"

I got the above error: KeyError: 'http_headers'

In YoutubeDL.py line 1894, code:
`dl(sub_filename, sub_info, subtitle=True)`
The dict sub_info comes from subtitles and it has no key 'http_headers'. But in external.py line 192, have the following code:

```
class Aria2cFD(ExternalFD):
    ...
    def _make_cmd(self, tmpfilename, info_dict):
        ...
        for key, val in info_dict['http_headers'].items():
            cmd += ['--header', '%s: %s' % (key, val)]`
        ...
```

The info_dict is sub_info,  but there is no 'http_headers' in it, raise this error.
Please fix soon, very grateful!

**Comment by awei78** [comment]
```
        dict = info_dict['http_headers'] if 'http_headers' in info_dict else info_dict
        for key, val in dict.items():
            cmd += ['--header', '%s: %s' % (key, val)]
```
