### ISSUE TITLE
YT Playlist has another issue in latest release: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by chrisr11** [blackjack4494/yt-dlc#167]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.11.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-4', u'-q', u'--no-warnings', u'-J', u'--flat-playlist', u'https://www.youtube.com/playlist?list=PLOHoVaTp8R7dfrJW5pumS0iD_dhlXKv17']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dlc version 2020.11.11-1
[debug] Python version 2.7.17 (CPython) - Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dlc/__main__.py", line 19, in <module>
  File "/usr/local/bin/youtube-dlc/youtube_dlc/__init__.py", line 487, in main
  File "/usr/local/bin/youtube-dlc/youtube_dlc/__init__.py", line 477, in _real_main
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 2104, in download
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 846, in extract_info
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1007, in process_ie_result
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 377, in _entries
TypeError: str() takes at most 1 argument (2 given)
[debug] Loading archive file None
```

## Description

I have compiled the latest release (v2020.11.11) and the playlist extractor throws the above error for some playlists, such as: 

https://www.youtube.com/playlist?list=PLOHoVaTp8R7dfrJW5pumS0iD_dhlXKv17
https://www.youtube.com/playlist?list=UU_aEa8K-EOJ3D6gOs7HcyNg

**Comment by blackjack4494** [comment]
#168
