### ISSUE TITLE
YouTube download error: HTTP Error 500: Internal Server Error.

### ISSUE THREAD

**Issue by chrisr11** [blackjack4494/yt-dlc#174]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dlc version **2020.11.11**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'best', u'https://youtu.be/sIdxd-wbPgE']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 2.7.16 (CPython) - Darwin-19.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sIdxd-wbPgE: Downloading webpage
[youtube] sIdxd-wbPgE: Downloading MPD manifest
[debug] Invoking downloader on u'https://r5---sn-cxaaj5o5q5-tt1y.googlevideo.com/videoplayback?expire=1605131805&ei=vQmsX83SDJnnhwapmr6QDQ&ip=207.35.98.9&id=o-AFrrzsWgNvUha8Mfx4wesFnoMpW7ZFQmMwUXSAZVyKeo&itag=22&source=youtube&requiressl=yes&mh=S_&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1y%2Csn-t0a7ln7d&ms=au%2Conr&mv=m&mvi=5&pl=17&initcwndbps=673750&vprv=1&mime=video%2Fmp4&ns=3rDpJHih5VGYo6g5S9FkfvcF&ratebypass=yes&dur=4906.678&lmt=1582471181340253&mt=1605110078&fvip=5&beids=23886206&c=WEB&n=926nvz_3opCnS4wQWu&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALhK8u_dej9J4ri56tFS6foKBpTNqHWlCeH0M3Y9dpqvAiBJV_BoqnwG-_sYzjjeZFHx_ecI3eAaup3qvrq0APCeEg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMN_6SjQs31AR7FxyWfGy0R8vX3krqJqPT-VESLWctezAiA3UrXMjHFfseIZ78Upn8KD6w_A6KLNFI1Z7ooYREY0Lg%3D%3D'
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/Users/Macintosh/Desktop/youtube-dlc/youtube_dlc/downloader/http.py", line 349, in real_download
    establish_connection()
  File "/Users/Macintosh/Desktop/youtube-dlc/youtube_dlc/downloader/http.py", line 187, in establish_connection
    raise RetryDownload(err)
RetryDownload
```

## Description

I'm unable to download these videos when I specify the video quality that I want using the '-f' argument:

https://youtu.be/PKVRTh5lCJU
https://youtu.be/DQSfSH4KmU0
https://youtu.be/sIdxd-wbPgE
https://youtu.be/oAYNWPiBHO8

It throws the following error: [download] Got server HTTP error: HTTP Error 500: Internal Server Error. Retrying

**Comment by blackjack4494** [comment]
try using watch url.

**Comment by chrisr11** [comment]
> try using watch url and force ipv4

Yes, I used '-4' to force ipv4. How can I use "watch url"?

**Comment by chrisr11** [comment]
@blackjack4494 

> try using watch url and force ipv4

Same issue with "?watch" URL and forcing IPV4. Any idea why this is happening?

**Comment by blackjack4494** [comment]
are you using vpn or anything? It's got to be something with your connection.
