### ISSUE TITLE
[Broken] same.  --  You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: https://github.com/ytdl-org/youtube-dl/issues/25871#issuecomment-653207803

### ISSUE THREAD

**Issue by anonvoy** [blackjack4494/yt-dlc#191]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31** - actually it's even **2020.11.11-3**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-i', u'-f', u'best[height<=720]', u'-o', u'/home/abc/Down/NBC/NBC_Nightly_News-%(upload_date)s-%(title)s.%(ext)s', u'https://www.nbcnews.com/nightly-news-netcast/video/nightly-news-full-broadcast-november-12th-95829061895']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 2.7.17 (CPython) - Linux-4.12.14-lp151.28.79-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 3.4.5, ffprobe 3.4.5
[debug] Proxy map: {}
[NBCNews] 95829061895: Downloading webpage
ERROR: Unable to extract bootstrap json; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/nbc.py", line 398, in _real_extract
    'bootstrap json'), video_id, js_to_json)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract bootstrap json; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

```

## Description

The NBC news extractor doesn't work anymore. It broke in early July.

**Comment by yonap** [comment]
#Edeheeeeeeeejeedeeeedjeeeeedeweeedejeeeedeeeeeeeeeeeeeddedeeedeeeedeweeeeeeedeeeeededeeeeeeeeeqeeeeeeeeeeedeweedeeeeeeeeegeeehjjnejesn dedeneneejeje.ed.e.eejd.dnj.jnh.j..qn..ened.ededd.jd.eweeeeeddej..edd.j.de.eedeh.3.ewee.qeee.eq.eeee.e.d.d.eëeedwe weeedeweeeeeeeedeeeeeeeeeeq.ee3eweeeeqj.hqqj.e'enh.ne .e.nbh.bchhh..qhhsc ehhenhemgeweg sfn.wwswhhfhmmsgwhehGBqhmmfw wghfGBsbffh.qffh egq.gzm qh .whwwsm.gwwhgehghqgjwhwghwfwgegwFMwwgwfhhwgwgwwgfwgggjwwhwweffwgfffwghgfwfhwwwhswwqfhhhw- - qffwhhhfwhhwwfwfsqqwwhwqhhwhwh- hhwhwhwwwwwwwwwqwwwwwwwwwwwwwwwwwwwwwwwhwwffhfwwqwwwwwhwhwhhwqhwhhhwhhhhhhqhww&h- hqhhhhqhwqhqhhwhhqhqwhwhwhwhwwhhhwhwqqhwhwwwhwwwhqwqhhqwhq- hwwhwhwhwwwwwwqwwwwwwwwwwwwwwwwwwwqwwqwwwwqwwwwwwwwwwwwwwwwqwwwwww2wwwwwwwwwwwwwwwwwwwwwwwwwwwwqwwwwwewwwwwwwwhhfh.hv ehfhg.gghhf.h.ffgqfh.ghfw.bb.f.wf.h.hFMhfh..hwwhhwehwwhqhwhwhqwhwwhhwwq&qhwhqwwhehwhwhwwhwwwwerewhwwhqhwhqhfhwwhhwwhehhww222qwwww2w22wwwwwwwwwwwww2wwwwwwwww22www2wwwehwqhfhehhhewhqehwhqhqwwhhwhwwqhwhhhqwhwhehhqwhhwwhhhhwhhqwhwhwhhwqehqwhwhehhfhfwhwhqffehwhwqhhwwwhqhwqwhhqqwww2whwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by october262** [comment]
use the Firefox addon called the stream detector to grab the m3u8 files
and set it to  youtube-dlc command then just open a terminal and just right click
and paste into terminal to download the video.

**Comment by anonvoy** [comment]
> use the Firefox addon called the stream detector to grab the m3u8 files
> and set it to youtube-dlc command then just open a terminal and just right click
> and paste into terminal to download the video.

That won't work with Flexget automation unfortunately.
