### ISSUE TITLE
[Broken] TikTok channel page

### ISSUE THREAD

**Issue by AplhaSlayer1964** [blackjack4494/yt-dlc#195]
## Checklist

- [ X ] I'm reporting a broken site support
- [ X ] I've verified that I'm running youtube-dlc version **2020.10.31**
- [ X ] I've checked that all provided URLs are alive and playable in a browser
- [ X ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.tiktok.com/@tiktok']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-09-21-full_build-www.gyan.dev, ffprobe 4.3.1-2020-09-21-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] @tiktok: Requesting header
WARNING: Falling back on generic information extractor.
[generic] @tiktok: Downloading webpage
[generic] @tiktok: Extracting information
ERROR: Unsupported URL: https://www.tiktok.com/@tiktok
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\generic.py", line 3382, in _real_extract
youtube_dlc.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@tiktok
```

## Description

First I know titktok seems to always break but I still wanted to ask.
youtube-dlc doesn't download all the videos of a given tiktok page. Individual videos work but not entire pages.

**Comment by fosam** [comment]
I confirm, TikTokUser is broken.

![Capture 16_11_2020_00_17_40](https://user-images.githubusercontent.com/52612348/99199685-348ff680-27a1-11eb-8e66-6925fbbd85bd.png)

**Comment by sjvdmerwe** [comment]
Hello, apologies for linking outside of this project however the following GitHub project does currently allow you to download a TikTok user's content.

https://github.com/drawrowfly/tiktok-scraper/

**Comment by fosam** [comment]
Hi, it is not packaged, it has to be compiled?

**Comment by sjvdmerwe** [comment]
Hello, you can install it using npm then run it as a standard program on linux.

**Comment by AplhaSlayer1964** [comment]
Ya I used that for a bit but it always breaks for me. Even when I only use one user and tell it to only scrape the first 20 posts.

**Comment by sjvdmerwe** [comment]
Your issue sounds very odd, I have used it to download 2600 videos from a single account.

The command I used,

tiktok-scraper user USERNAME --hd -a 10 -d -t "csv" -w

**Comment by fosam** [comment]
It is also easier to download using dlc

**Comment by AplhaSlayer1964** [comment]
@sjvdmerwe I will see if it needs to be updates and try messing with it a bit more.
Doing some testing there are probably gonna need to do a lot of background stuff to get tiktok fully working as even if you feed it a bunch of links you get rate limited really fast it seems.
