### ISSUE TITLE
Could not find XML element title

### ISSUE THREAD

**Issue by tv21** [blackjack4494/yt-dlc#206]
$ youtube-dlc --verbose https://www.cbs.com/shows/the-unicorn/video/ZlEfHIHOKkLTDAOQb5YSz8m_wdiKiCZw/the-unicorn-there-s-something-about-whoever-she-was/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.cbs.com/shows/the-unicorn/video/ZlEfHIHOKkLTDAOQb5YSz8m_wdiKiCZw/the-unicorn-there-s-something-about-whoever-she-was/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-12-686-pae-i686-with-debian-10.6
[debug] exe versions: avconv 4.1.6-1, avprobe 4.1.6-1, ffmpeg 4.3-static, ffprobe 4.3-static, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] ZlEfHIHOKkLTDAOQb5YSz8m_wdiKiCZw: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/cbs.py", line 112, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/cbs.py", line 62, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/utils.py", line 1910, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/utils.py", line 1903, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
ExtractorError: Could not find XML element title; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

(Also tried forcing it to run under Python3 with same result)

**Comment by stvrly** [comment]
Looks to be an issue with multiple CBS programs. Seeing it here with NCIS NoLa and LA. For example:

```
# youtube-dlc --verbose --output "S12E01 - The Bear.mp4" https://www.cbs.com/shows/ncis_los_angeles/video/XQm
A4fYxYp4fOUlkgAq4YhwlBJLLtJ1a/ncis-los-angeles-the-bear/
[debug] System config: ['--verbose', '--hls-prefer-native', '--format', 'best', '--output', '%(upload_date)s %(title)s.%(ext)s']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--output', 'S12E01 - The Bear.mp4', 'https://www.cbs.com/shows/ncis_los_angeles/video/XQmA4fYxYp4fOUlkgAq4YhwlBJLLtJ1a/ncis-los-angeles-the-bear/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.5 (CPython) - Linux-5.4.0-53-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[CBS] XQmA4fYxYp4fOUlkgAq4YhwlBJLLtJ1a: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/cbs.py", line 112, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/cbs.py", line 62, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/utils.py", line 1910, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/utils.py", line 1903, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dlc.utils.ExtractorError: Could not find XML element title; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

Running:
```
# youtube-dlc --version
2020.11.11-3
```

**Comment by october262** [comment]
tried with both with the Firefox addon  the stream detector and video downloadhelper 
the stream detector - gets the MPD stream but unable to download
video downloadhelper - might just work on this episode as it's grabbing the mp4
