### ISSUE TITLE
[Vlive] Program crashes when a channel contains playlist

### ISSUE THREAD

**Issue by kyuyeunk** [blackjack4494/yt-dlc#222]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.vlive.tv/channel/CB0685', '--playlist-start', '36', '-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-2
[debug] Git HEAD: d052b9a11
[debug] Python version 3.8.5 (CPython) - Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[vlive:channel] CB0685: Downloading webpage
[vlive:channel] CB0685: Downloading decode channel code
[vlive:channel] CB0685: Downloading channel list page #1
[vlive:channel] CB0685: Downloading channel list page #2
[vlive:channel] CB0685: Downloading channel list page #3
[vlive:channel] CB0685: Downloading channel list page #4
[vlive:channel] CB0685: Downloading channel list page #5
[vlive:channel] CB0685: Downloading channel list page #6
[vlive:channel] CB0685: Downloading channel list page #7
[vlive:channel] CB0685: Downloading channel list page #8
[vlive:channel] CB0685: Downloading channel list page #9
[download] Downloading playlist: 아이돌룸(IDOL ROOM)
[vlive:channel] playlist 아이돌룸(IDOL ROOM): Collected 751 video ids (downloading 716 of them)
[download] Downloading video 1 of 716
[vlive] 113852: Downloading webpage
ERROR: Failed to extract video parameters.; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/kyu/dev/yt-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/home/kyu/dev/yt-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/home/kyu/dev/yt-dlc/youtube_dlc/extractor/vlive.py", line 144, in _real_extract
    raise ExtractorError('Failed to extract video parameters.')
youtube_dlc.utils.ExtractorError: Failed to extract video parameters.; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

In the channel https://www.vlive.tv/channel/CB0685, 36th entry is a playlist. And trying to download the entry results in the error.

**Comment by blackjack4494** [comment]
got fixed by #224
