### ISSUE TITLE
[Youtube] Extraction of subs fails for certain videos, crashes process

### ISSUE THREAD

**Issue by jorong1** [blackjack4494/yt-dlc#24]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
Since bugtracker is quite new, and the old one is under DMCA, I'm unsure if this was reported before.

## Verbose log
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: [u'-f', u'bestvideo[ext=webm]+bestaudio[ext=webm]/bestvideo+bestaudio', u'-i', u'-o', u'%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - [%(resolution)s] [%(id)s].%(ext)s', u'--ffmpeg-location', u'./ffmpeg', u'--download-archive', u'youtube-dl-archive.txt', u'-a', u'youtube-dl-channels.txt', u'--prefer-ffmpeg', u'--merge-output-format', u'mkv', u'--write-sub', u'--all-subs', u'--convert-subs', u'srt', u'--add-metadata', u'--write-description', u'--write-thumbnail', u'-v']
[debug] Command-line args: [u'--config-location', u'./youtube-dl.conf']
[debug] Batch file urls: [u'https://www.youtube.com/channel/UCxLYtICsUCWdr1YPrj5DtwA']
[debug] Loading archive file u'youtube-dl-archive.txt'                                                               
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8                                                     
[debug] youtube-dlc version 2020.10.26                                                                               
[debug] Python version 2.7.16 (CPython) - Linux-5.6.0-0.bpo.2-amd64-x86_64-with-debian-10.6                          
[debug] exe versions: ffmpeg N-45774-g223f3dff8-static                                                               
[debug] Proxy map: {}
[youtube:playlist] UUxLYtICsUCWdr1YPrj5DtwA: Downloading webpage
[download] Downloading playlist: Uploads from Ordinary Things
[youtube:playlist] playlist Uploads from Ordinary Things: Downloading 36 videos
[download] Downloading video 1 of 36
[download] The Evil Economics of Tinder has already been recorded in archive
[download] Downloading video 2 of 36
[download] Handshakes Deserve to Die, Here's Why has already been recorded in archive
[download] Downloading video 3 of 36
[download] Why the Internet Hates Nestlé has already been recorded in archive
[download] Downloading video 4 of 36
[download] How to WIN an Election | An Ordinary Guide has already been recorded in archive
[download] Downloading video 5 of 36
[download] The Bloody Business of the British Flag has already been recorded in archive
[download] Downloading video 6 of 36
[download] The Tasteless History of Ronald McDonald has already been recorded in archive
[download] Downloading video 7 of 36
[download] How Nintendo Killed the GameCube has already been recorded in archive
[download] Downloading video 8 of 36
[download] The Great Egg Industry InfoWar has already been recorded in archive
[download] Downloading video 9 of 36
[download] How the USSR Collapsed on Soviet TV has already been recorded in archive
[download] Downloading video 10 of 36
[download] The Billion-Dollar Bitcoin Scam has already been recorded in archive
[download] Downloading video 11 of 36
[download] The Bizarre Business of Trading Cards has already been recorded in archive
[download] Downloading video 12 of 36
[download] The Rise & Fall of American Malls has already been recorded in archive
[download] Downloading video 13 of 36
[download] Unmasking The History of Masks has already been recorded in archive
[download] Downloading video 14 of 36
[download] The Toxic Business of Cruise Ships has already been recorded in archive
[download] Downloading video 15 of 36
[info] Writing video description to: Ordinary Things (UCxLYtICsUCWdr1YPrj5DtwA)/20200320 - The Desperate History of Panic Buying - [1920x1080] [ZX4vseaNJKY].description
[info] Writing video subtitles to: Ordinary Things (UCxLYtICsUCWdr1YPrj5DtwA)/20200320 - The Desperate History of Panic Buying - [1920x1080] [ZX4vseaNJKY].live_chat.json
ERROR: u'url'
Traceback (most recent call last):
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 841, in extract_info                      
    return self.process_ie_result(ie_result, download, extra_info)                                                   
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 896, in process_ie_result                 
    return self.process_video_result(ie_result, download=download)                                                   
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1691, in process_video_result             
    self.process_info(new_info)
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1893, in process_info                     
    sub_info['url'], info_dict['id'], note=False).read()
KeyError: u'url'

[download] Downloading video 16 of 36
[youtube] 9k6sbhyOD5o: Downloading webpage
[youtube] 9k6sbhyOD5o: Downloading embed webpage
[youtube] 9k6sbhyOD5o: Refetching age-gated info webpage
[info] Writing video description to: Ordinary Things (UCxLYtICsUCWdr1YPrj5DtwA)/20200306 - The (Ob)Noxious Rise of Vapes - [1920x1080] [9k6sbhyOD5o].description
[info] Writing video subtitles to: Ordinary Things (UCxLYtICsUCWdr1YPrj5DtwA)/20200306 - The (Ob)Noxious Rise of Vapes - [1920x1080] [9k6sbhyOD5o].live_chat.json
ERROR: u'url'
Traceback (most recent call last):
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 841, in extract_info                      
    return self.process_ie_result(ie_result, download, extra_info)                                                   
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 896, in process_ie_result                 
    return self.process_video_result(ie_result, download=download)                                                   
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1691, in process_video_result             
    self.process_info(new_info)
  File "/home/user/.local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 1893, in process_info                     
    sub_info['url'], info_dict['id'], note=False).read()
KeyError: u'url'

^C
ERROR: Interrupted by user
```

## Description
youtube-dlc seems to fail grabbing subtitles for videos, even if there aren't any, and is instead grabbing **live_chat.json** files, which don't exist for these videos.
This in turn crashes the video ID grab process, which skips grabbing the video all together.

If I comment out these subs lines in my .conf, it grabs video and description without issue. It of course does not grab subs.
```
# Get All Subs to SRT
--write-sub
--all-subs
--convert-subs srt
```
youtube-dl 2020.09.20 fails to parse or even download the videos.
Thanks!

**Comment by im-coooding** [comment]
You can use `--sleep-subtitles` as a temporary workaround for this. The live chats do actually exist for those videos, and gets downloaded correctly as long as that flag is enabled. The problem is caused by live chats needing a special downloader, which isn't used by the non-sleep code.
