### ISSUE TITLE
Fox not working

### ISSUE THREAD

**Issue by jriker1** [blackjack4494/yt-dlc#244]
When I try to convert a video from Fox.com I get the below error.  as you can see from my call I am passing the Comcast login info as I do with other networks.

C:\Users\jriker\source\repos\ShowWebsiteDownloader\ShowWebsiteDownloader\bin\Debug>youtube-dlc --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username jriker --ap-password PASSWORD https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965 -o "The Masked Singer S4E8.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965', '-o', 'The Masked Singer S4E8.mp4', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[FOX] Downloading JSON metadata
[FOX] fac8008934fc490dc6e29fef9d22f965: Downloading JSON metadata
ERROR: This video is only available via cable service provider subscription. You may want to use --cookies.
Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2316, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\fox.py", line 65, in _call_api
    return self._download_json(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\adobepass.py", line 1336, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dlc.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2316, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\fox.py", line 65, in _call_api
    return self._download_json(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 893, in _download_json
    res = self._download_json_handle(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 872, in _download_json_handle
    res = self._download_webpage_handle(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\adobepass.py", line 1336, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 665, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 650, in _request_webpage
    raise ExtractorError(errmsg, sys.exc_info()[2], cause=err)
youtube_dlc.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\fox.py", line 96, in _real_extract
    video = self._call_api('vodplayer/' + video_id, video_id)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\fox.py", line 74, in _call_api
    raise ExtractorError(
youtube_dlc.utils.ExtractorError: This video is only available via cable service provider subscription. You may want to use --cookies.

**Comment by jriker1** [comment]
Should also be noted if I did it right, that I tried creating a cookie file and pointing to it but oddly youtube-dlc says the same thing to try using --cookies so either it's a standard output even if it was entered or it's being ignored.

**Comment by merval** [comment]
I just ran it without specifying anything and it worked. What happens if you don't specify any credentials?
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.fox.com/watch/fac8008934fc490dc6e29fef9d22f965', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-2
[debug] Git HEAD: 93201d50a
[debug] Python version 3.7.3 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] Downloading JSON metadata
[FOX] fac8008934fc490dc6e29fef9d22f965: Downloading JSON metadata
[FOX] fac8008934fc490dc6e29fef9d22f965: Downloading JSON metadata
[FOX] fac8008934fc490dc6e29fef9d22f965: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://content-ausc3.uplynk.com/12cd0f7651e242e5a4aa688ce5034c32/k.m3u8?pbs=80b2e8c381ec410591819e2221557eb7'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 635 (not including 293 ad)
[download] Destination: The Group B Finals - The Mask Chance Saloon-fac8008934fc490dc6e29fef9d22f965.mp4
[download]  46.5% of ~1.58GiB at  7.56MiB/s ETA 02:34
```

**Comment by blackjack4494** [comment]
closing this for now. feel free to keep discussing.
