### ISSUE TITLE
CBS maybe all access?

### ISSUE THREAD

**Issue by jriker1** [blackjack4494/yt-dlc#251]
I get some level of access to CBS with my XFinity account.  I was able to retrieve the latest show from Star Trek Discovery but when I tried to retrieve the latest version of The Neightborhood it failed and was able to play it thru Chrome.  Call I'm doing is: and the couldn't find the XML element title is probably relevant:

youtube-dlc --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username jriker1 --ap-password PASSWORD https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/

[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[CBS] hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_: Downloading XML
ERROR: Could not find XML element title; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\cbs.py", line 112, in _real_extract
    return self._extract_video_info(content_id)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\cbs.py", line 62, in _extract_video_info
    title = xpath_text(video_data, 'videoTitle', 'title', True)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\utils.py", line 1910, in xpath_text
    n = xpath_element(node, xpath, name, fatal=fatal, default=default)
  File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\utils.py", line 1903, in xpath_element
    raise ExtractorError('Could not find XML element %s' % name)
youtube_dlc.utils.ExtractorError: Could not find XML element title; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

**Comment by october262** [comment]
this link -  https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/

has DRM protection
same issue as this - https://github.com/ytdl-org/youtube-dl/issues/27089

**Comment by jriker1** [comment]
Thanks and odd.  You would think a standard network show they wouldn't put so much effort to block downloading of.  Not sure how DRM protection works and all with direct downloading of the files and the error sounds like something is missing but will take your word for it.  Especially since other shows that are CBS All Access only they don't block.  Or maybe they are working on it.

**Comment by jriker1** [comment]
Side question for future ability to troubleshoot.  How do you tell it's DRM protected?

**Comment by october262** [comment]
> Side question for future ability to troubleshoot. How do you tell it's DRM protected?

just google "how to tell if video is DRM protected"

**Comment by keith-leitch** [comment]
> 
> 
> this link - https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/
> 
> has DRM protection
> same issue as this - [ytdl-org/youtube-dl#27089](https://github.com/ytdl-org/youtube-dl/issues/27089)

This cannot be DRM, @october262. I just downloaded that same episide of The Neighborhood from the same link. No problems. Similarly with issue 27089, I commented there that I was able to download @jriker1 's "Seal Team" video, but not some others.

Let's all please not be so quick to write this off as DRM. Different users are getting different results with different CBS videos... or, CBS downloads are failing for awhile, then succeeding later.

@jriker1, can you please try The Neighborhood and Seal Team again and report your results? Better yet, can you also visit https://github.com/ytdl-org/youtube-dl/issues/27089 and try the failed "The Unicorn" link that I posted there?

**Comment by october262** [comment]
> > this link - https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/
> > has DRM protection
> > same issue as this - [ytdl-org/youtube-dl#27089](https://github.com/ytdl-org/youtube-dl/issues/27089)
> 
> This cannot be DRM, @october262. I just downloaded that same episide of The Neighborhood from the same link. No problems. Similarly with issue 27089, I commented there that I was able to download @jriker1 's "Seal Team" video, but not some others.
> 
> Let's all please not be so quick to write this off as DRM. Different users are getting different results with different CBS videos... or, CBS downloads are failing for awhile, then succeeding later.
> 
> @jriker1, can you please try The Neighborhood and Seal Team again and report your results? Better yet, can you also visit [ytdl-org/youtube-dl#27089](https://github.com/ytdl-org/youtube-dl/issues/27089) and try the failed "The Unicorn" link that I posted there?
> 
> ...and yes, OTA with a DVR is the way to go.

this link - https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/ now works with both youtube-dl & dlc so unsure as to why it didn't
work the first time.

**Comment by keith-leitch** [comment]
Understood, but it's not an isolated case. Users are reporting this download error from CBS in thread after thread using both dl and dlc, but I can always download from the links they report using both projects. There are other links from other shows where I get the error. Check https://github.com/blackjack4494/yt-dlc/issues/275 as another of many examples.

**Comment by october262** [comment]
> Understood, @october262, but it's not an isolated case. Users are reporting this download error from CBS in thread after thread using both dl and dlc, but I can always download from the links they report using both projects. There are other links from other shows where I get the error. Check #275 as another of many examples.

youtube-dl is now able to detect DRM protected videos now - https://www.videohelp.com/software/youtube-dl/version-history 
see under youtube-dl 2020.12.02

**Comment by keith-leitch** [comment]
What I'm hoping to impress on everyone is that the "Could not find XML Element" error, being reported so often from CBS.com, cannot be a DRM issue. It just makes no sense, for these reasons:

1. CBS would not add DRM then take it off later. The list below shows links that "didn't work" then "did work" a few days later.

2. I can't see why CBS would add DRM to OTA videos but not to Subscription videos. The list below shows that the latest episode of "Star Trek: Discovery" works.

3. If youtube-dl updates solved the problem, then all videos would now work. Some still don't. I am not adding the full bug report for these, because I think the problem's been reported to death. If someone thinks I should, then I will.

4. The error message does not mention DRM. It says that the downloader "Could not find the XML element.' I'm inclined to take that message at face value, and conclude that the script is sometimes missing the metadata that the downloader needs.

Examples of CBS videos that youtube-dl/c could not download before, but now can. It would be weird in the extreme for CBS to add DRM, then remove it days later.

 https://www.cbs.com/shows/the-neighborhood/video/hybfwzvq_TWhJJSE4FXfT_vQB9Ky3Sr_/the-neighborhood-welcome-to-the-movement/
https://cbs.com/shows/seal-team/video/a4Af8ptKlr5gthauHnde5C9JdeJcNnWa/seal-team-god-of-war-forever-war/
https://www.cbs.com/shows/ncis-new-orleans/video/_2DEJoZKRPsStgPJrekAJ5wMph_qM2jO/ncis-new-orleans-something-in-the-air-part-2/

Examples of CBS videos that youtube-dl/c can't download today. These show that the youtube-dl patch mentioned by @october262 has not addressed this issue. Also, youtube-dlc downloads the list above, but not below.

https://www.cbs.com/shows/ncis/video/656bTfET07GnL8vgDviQnyaOwGKdaF2W/ncis-sturgeon-season/
https://www.cbs.com/shows/ncis/video/JJqb_JEapMBMVdn7FYsQMqBamGyQhaTQ/ncis-everything-starts-somewhere/
https://www.cbs.com/shows/ncis/video/HAvQcadOM_QgDzFd6yK8BZm5iTgkZCta/ncis-blood-and-treasure/
https://www.cbs.com/shows/the-unicorn/video/ZlEfHIHOKkLTDAOQb5YSz8m_wdiKiCZw/the-unicorn-there-s-something-about-whoever-she-was/
https://www.cbs.com/shows/the-unicorn/video/UqeHafhusoogPFU_YGNbfDxUYE4wkm6Z/the-unicorn-it-s-complicated/
https://www.cbs.com/shows/the-unicorn/video/72nFb7mACKi28mWkfV09uMsIKqfmkdqT/the-unicorn-it-s-the-thought-that-counts/

Examples of CBS videos that work just fine today. Notice that one of these is subscription-only. It would be weird in the extreme for CBS to add DRM to OTA video, but not subscription. Notice also that this video and the others are newer than the failures above. It would be weird in the extreme for CBS to add DRM to older videos, but not newer.

https://www.cbs.com/shows/bob-hearts-abishola/video/e3Dis09PuIcoec0ADzv7XKJGsEtw9vhw/bob-hearts-abishola-camp-bananas/
https://www.cbs.com/shows/magnum-pi/video/o_eBPsGoVAeXvXg_fozxT88bfunT_HqP/magnum-p-i-easy-money/
https://www.cbs.com/shows/young-sheldon/video/Fmt0hKA3hj05An8XK3hl_ZGmw_xgvKKp/young-sheldon-bible-camp-and-a-chariot-of-love/
https://www.cbs.com/shows/star-trek-discovery/video/73BJ1N0qerkG0WPoUKNuDPcvBdvD6fEX/star-trek-discovery-terra-firma-part-1/

The only logical conclusion is that this is not, in fact, a DRM issue. It seems like stamping a problem "DRM" is always the simplest answer, but it just makes no sense, here. I wish I was better with Python so that I could be more help, but I hope that someone who is can see the logic of my argument.

**Comment by keith-leitch** [comment]
Just to add some evidence to my argument that this is not a DRM issue:

I found this episode on CBS, posted yesterday. Ytdl/c both download it perfectly, right from day one (no waiting, no application and later removal of DRM, etc.). Just to be clear, Ytdl finds the XML file, extracts the metadata, downloads the file and then I watch it.

https://www.cbs.com/shows/bob-hearts-abishola/video/73gHAdnlAl72H2jhijTK_U2IE4ECYLwu/bob-hearts-abishola-sleeping-next-to-an-old-boat

However, when I go after the segments manually, as @jriker1 describes above, the result is encrypted. The encryption results in exactly the same way for manual downloads that do or do not experience the XML error when using ytdl/c. This is more evidence that the CBS/XML error is not caused by DRM.

I was thinking about some of the shows above (The Neighborhood, Seal Team) that suddenly "started working." The time that this happened could coincide with the latest ytdl update in December.
