### ISSUE TITLE
[YT] subscriptions do not work

### ISSUE THREAD

**Issue by konomikitten** [blackjack4494/yt-dlc#252]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--cookies', 'cookies.txt', 'https://www.youtube.com/feed/subscriptions']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-2
[debug] Git HEAD: 228385340
[debug] Python version 3.8.6 (CPython) - Linux-5.7.0-3-amd64-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
ERROR: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/debian/Resources/GitHub/anonymous/yt-dlc/youtube_dlc/YoutubeDL.py", line 858, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/debian/Resources/GitHub/anonymous/yt-dlc/youtube_dlc/YoutubeDL.py", line 1018, in process_ie_result
    entries = list(itertools.islice(
  File "/home/debian/Resources/GitHub/anonymous/yt-dlc/youtube_dlc/extractor/youtube.py", line 341, in _entries
    data_json = self._parse_json(self._search_regex(self._INITIAL_DATA_RE, page, 'ytInitialData'), None)
  File "/home/debian/Resources/GitHub/anonymous/yt-dlc/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dlc.utils.RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Subscriptions for YouTube have been broken for a long time, be nice to get them fixed.

**Comment by pukkandan** [comment]
`:ytsubs` works. only the URL is broken

**Comment by pukkandan** [comment]
It is working for me. Are you sure your cookies are valid?

**Comment by konomikitten** [comment]
Apparently I used the wrong cookie file due to confusion on my part with Firefox Containers (you get two sets of cookies for containers).
