### ISSUE TITLE
Merge webm and opus into mp4 error

### ISSUE THREAD

**Issue by ExodusHour** [blackjack4494/yt-dlc#263]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Trying to download this video on my raspberry pi https://www.youtube.com/watch?v=2lhzBlaAqY4 I get an error when the video and audio are try to merge into mp4. I tried updating my ffmpeg but it's already the newest version. When I run the same command on my windows 10 pc it merges into mp4 with no errors. Not sure why it doesn't work on my raspberry pi.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '-f', '(bestvideo[vcodec^=vp9][height>4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=vp9][height>2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=vp9][height>2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=vp9][height>1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=vp9][height>1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=vp9][height>720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=vp9][height>720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=vp9][height>480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=vp9][height>480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=vp9][height>360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=vp9][height>360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=vp9][height>240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=vp9][height>240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=vp9][height>144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=vp9][height>144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best', '--merge-output-format', 'mp4', '--write-thumbnail', '--write-sub', '--all-subs', '--embed-subs', '--add-metadata', '-v', '2lhzBlaAqY4']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.3 (CPython) - Linux-5.4.72-v7l+-armv7l-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
```
```
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/youtube_dlc/YoutubeDL.py", line 2150, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dlc/postprocessor/ffmpeg.py", line 551, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.7/dist-packages/youtube_dlc/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dlc.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```
windows 10 verbose
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-i', '-f', '(bestvideo[vcodec^=vp9][height>4320][fps>30]/bestvideo[vcodec^=vp9.2][height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec^=avc1][height>=4320][fps>30]/bestvideo[height>=4320][fps>30]/bestvideo[vcodec^=vp9][height>4320]/bestvideo[vcodec^=vp9.2][height>=4320]/bestvideo[vcodec^=av01][height>=4320]/bestvideo[vcodec^=avc1][height>=4320]/bestvideo[height>=4320]/bestvideo[vcodec^=vp9][height>2880][fps>30]/bestvideo[vcodec^=vp9.2][height>=2880][fps>30]/bestvideo[vcodec^=av01][height>=2880][fps>30]/bestvideo[vcodec^=avc1][height>=2880][fps>30]/bestvideo[height>=2880][fps>30]/bestvideo[vcodec^=vp9][height>2880]/bestvideo[vcodec^=vp9.2][height>=2880]/bestvideo[vcodec^=av01][height>=2880]/bestvideo[vcodec^=avc1][height>=2880]/bestvideo[height>=2880]/bestvideo[vcodec^=vp9][height>2160][fps>30]/bestvideo[vcodec^=vp9.2][height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec^=avc1][height>=2160][fps>30]/bestvideo[height>=2160][fps>30]/bestvideo[vcodec^=vp9][height>2160]/bestvideo[vcodec^=vp9.2][height>=2160]/bestvideo[vcodec^=av01][height>=2160]/bestvideo[vcodec^=avc1][height>=2160]/bestvideo[height>=2160]/bestvideo[vcodec^=vp9][height>1440][fps>30]/bestvideo[vcodec^=vp9.2][height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec^=avc1][height>=1440][fps>30]/bestvideo[height>=1440][fps>30]/bestvideo[vcodec^=vp9][height>1440]/bestvideo[vcodec^=vp9.2][height>=1440]/bestvideo[vcodec^=av01][height>=1440]/bestvideo[vcodec^=avc1][height>=1440]/bestvideo[height>=1440]/bestvideo[vcodec^=vp9][height>1080][fps>30]/bestvideo[vcodec^=vp9.2][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec^=avc1][height>=1080][fps>30]/bestvideo[height>=1080][fps>30]/bestvideo[vcodec^=vp9][height>1080]/bestvideo[vcodec^=vp9.2][height>=1080]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec^=avc1][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=vp9][height>720][fps>30]/bestvideo[vcodec^=vp9.2][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec^=avc1][height>=720][fps>30]/bestvideo[height>=720][fps>30]/bestvideo[vcodec^=vp9][height>720]/bestvideo[vcodec^=vp9.2][height>=720]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec^=avc1][height>=720]/bestvideo[height>=720]/bestvideo[vcodec^=vp9][height>480][fps>30]/bestvideo[vcodec^=vp9.2][height>=480][fps>30]/bestvideo[vcodec^=av01][height>=480][fps>30]/bestvideo[vcodec^=avc1][height>=480][fps>30]/bestvideo[height>=480][fps>30]/bestvideo[vcodec^=vp9][height>480]/bestvideo[vcodec^=vp9.2][height>=480]/bestvideo[vcodec^=av01][height>=480]/bestvideo[vcodec^=avc1][height>=480]/bestvideo[height>=480]/bestvideo[vcodec^=vp9][height>360][fps>30]/bestvideo[vcodec^=vp9.2][height>=360][fps>30]/bestvideo[vcodec^=av01][height>=360][fps>30]/bestvideo[vcodec^=avc1][height>=360][fps>30]/bestvideo[height>=360][fps>30]/bestvideo[vcodec^=vp9][height>360]/bestvideo[vcodec^=vp9.2][height>=360]/bestvideo[vcodec^=av01][height>=360]/bestvideo[vcodec^=avc1][height>=360]/bestvideo[height>=360]/bestvideo[vcodec^=vp9][height>240][fps>30]/bestvideo[vcodec^=vp9.2][height>=240][fps>30]/bestvideo[vcodec^=av01][height>=240][fps>30]/bestvideo[vcodec^=avc1][height>=240][fps>30]/bestvideo[height>=240][fps>30]/bestvideo[vcodec^=vp9][height>240]/bestvideo[vcodec^=vp9.2][height>=240]/bestvideo[vcodec^=av01][height>=240]/bestvideo[vcodec^=avc1][height>=240]/bestvideo[height>=240]/bestvideo[vcodec^=vp9][height>144][fps>30]/bestvideo[vcodec^=vp9.2][height>=144][fps>30]/bestvideo[vcodec^=av01][height>=144][fps>30]/bestvideo[vcodec^=avc1][height>=144][fps>30]/bestvideo[height>=144][fps>30]/bestvideo[vcodec^=vp9][height>144]/bestvideo[vcodec^=vp9.2][height>=144]/bestvideo[vcodec^=av01][height>=144]/bestvideo[vcodec^=avc1][height>=144]/bestvideo[height>=144]/bestvideo)+(bestaudio[acodec^=opus]/bestaudio)/best', '--merge-output-format', 'mp4', '--write-thumbnail', '--write-sub', '--all-subs', '--embed-subs', '--add-metadata', '-v', '2lhzBlaAqY4']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-06-15-9d80f3e, ffprobe git-2020-06-15-9d80f3e
[debug] Proxy map: {}
[youtube] 2lhzBlaAqY4: Downloading webpage
WARNING: video doesn't have subtitles
[youtube] 2lhzBlaAqY4: Downloading thumbnail ...
[youtube] 2lhzBlaAqY4: Writing thumbnail to: Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.webp
[debug] Invoking downloader on 'https://r3---sn-p5qs7nes.googlevideo.com/videoplayback?expire=1606548291&ei=46bBX72qJoHJkwam47nIAQ&ip=71.82.130.80&id=o-AC4mPngO6x0aWFfLHdlWcuMfTarmmAkC6BJywI8Cy2j6&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=e4&mm=31%2C29&mn=sn-p5qs7nes%2Csn-vgqsknlk&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=2042500&vprv=1&mime=video%2Fmp4&ns=q7DSKl7Iv4THZmUPdkX17YQF&gir=yes&clen=101309492&dur=697.196&lmt=1577107691163158&mt=1606526205&fvip=3&keepalive=yes&c=WEB&txp=5432432&n=Hrc0C30WNALWlKlXwc1&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANZRMqxsdyvUow-NnFhOB0INCqSFb8y6TNuC4Qs6hQghAiEA4KHMUDLedqUI_wCtzt8on7FkUV5IBqzieNuevPAMucg%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgGOaCfZ2cFDaJce9vJyOjdZTcc49y0SveqJQ02mBjI2QCIAMVxoZO34Ak90f4qEE8EKwjG6FDcAhduVkPrYSkkFk3&ratebypass=yes'
[download] Destination: Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.f137.mp4
[download] 100% of 96.62MiB in 00:10
[debug] Invoking downloader on 'https://r3---sn-p5qs7nes.googlevideo.com/videoplayback?expire=1606548291&ei=46bBX72qJoHJkwam47nIAQ&ip=71.82.130.80&id=o-AC4mPngO6x0aWFfLHdlWcuMfTarmmAkC6BJywI8Cy2j6&itag=251&source=youtube&requiressl=yes&mh=e4&mm=31%2C29&mn=sn-p5qs7nes%2Csn-vgqsknlk&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=2042500&vprv=1&mime=audio%2Fwebm&ns=q7DSKl7Iv4THZmUPdkX17YQF&gir=yes&clen=8431564&dur=697.241&lmt=1604664631091567&mt=1606526205&fvip=3&keepalive=yes&c=WEB&txp=5511222&n=Hrc0C30WNALWlKlXwc1&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKtlnHSQiCCSy7Z9M6ZUHtPCSaaGBHTA-1xasC_dua6iAiEA07EBTmpuBLqM35wlrAR2yzCqNw60nvLbYw43mS9y-TA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgGOaCfZ2cFDaJce9vJyOjdZTcc49y0SveqJQ02mBjI2QCIAMVxoZO34Ak90f4qEE8EKwjG6FDcAhduVkPrYSkkFk3&ratebypass=yes'
[download] Destination: Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.f251.webm
[download] 100% of 8.04MiB in 00:00
[ffmpeg] Merging formats into "Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.f137.mp4" -i "file:Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.temp.mp4"
Deleting original file Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.f137.mp4 (pass -k to keep)
Deleting original file Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.f251.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.mp4" -map 0 -c copy -metadata "title=Making a SIMPLE handmade leather WALLET - ASMR" -metadata "date=20191223" -metadata "description=Sign up via my link and get 2 months FREE of Skillshare Premium!: https://skl.sh/littlekinggoods3
-metadata "purl=https://www.youtube.com/watch?v=2lhzBlaAqY4" -metadata "artist=Little King Goods" "file:Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.temp.mp4"
[ffmpeg] There aren't any subtitles to embed
```

**Comment by october262** [comment]
try youtube-dlc -f mp4 https://www.youtube.com/watch?v=2lhzBlaAqY4

**Comment by ExodusHour** [comment]
> try youtube-dlc -f mp4 https://www.youtube.com/watch?v=2lhzBlaAqY4

I tried that and got this, it downloads but doesn't download the best resoultion/bitrate or audio quality
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-f', 'mp4', 'https://www.youtube.com/watch?v=2lhzBlaAqY4', '-v']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.3 (CPython) - Linux-5.4.72-v7l+-armv7l-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube] 2lhzBlaAqY4: Downloading webpage
[debug] Invoking downloader on 'https://r3---sn-tt1eln7l.googlevideo.com/videoplayback?expire=1606562639&ei=797BX6jmOMOikgbrko-ACg&ip=192.252.213.218&id=o-AM69wohxhT9k5i3PsJnoUm97L3CGnRI7iCwTPV1OAxK1&itag=22&source=youtube&requiressl=yes&mh=e4&mm=31%2C29&mn=sn-tt1eln7l%2Csn-tt1e7n7k&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1230000&vprv=1&mime=video%2Fmp4&ns=HDPztQO04Amw6CrjUy-VsAIF&ratebypass=yes&dur=697.272&lmt=1577107754147005&mt=1606540604&fvip=3&c=WEB&txp=5432432&n=8yRO8FrMbK0Nu5msFXR&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQ4oAYbQJB4imf22mRMmWNKi26jTsR5zVlsdFmIWmkvQCIAxYg5OkFIX-trbuv8kKs85LFb52zQ1Z8xoSGP1vHyjt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAI6WdkYV7_c2r8ZxrG-uZ2WCsq6DCCoB2faj89rMS4WuAiA9DhJebe1VJLtaI12zrEAwZQoW1peiDC91QLwqsw704w%3D%3D'
[download] Destination: Making a SIMPLE handmade leather WALLET - ASMR-2lhzBlaAqY4.mp4
[download] 100% of 63.04MiB in 00:19
```

**Comment by october262** [comment]
run youtube-dlc -F https://www.youtube.com/watch?v=2lhzBlaAqY4 
to see all available formats for the video.

**Comment by ExodusHour** [comment]
> run youtube-dlc -F https://www.youtube.com/watch?v=2lhzBlaAqY4
> to see all available formats for the video.

Yes I know, I'm trying to download 248+251 which is webm+opus and I try to merge them into mp4 I get an error. When I do it on windows 10 it downloads and merges. I'm not sure you understand my problem. I'm having problems with 248+251 merging into mp4 on my raspberry pi when it has no problem merging on windows 10

**Comment by october262** [comment]
try youtube-dlc -f 248  https://www.youtube.com/watch?v=2lhzBlaAqY4  --recode-video mp4

**Comment by theincognito-inc** [comment]
@ExodusHour The merging should have worked, regardless of the platform.

Quick question: Are you sure the repos you use in Pi have the latest ffmpeg? Check the ffmpeg version you have in windows and the version you have in Pi. If the version in your Pi is lower than the one in Windows, there lies your problem.

**Comment by ExodusHour** [comment]
@theincognito-inc That's what I thought but I tired upgrading it on my pi and it said it's the newest version. It's version 4.1.6-1 while on Windows it's git-2020-06-15-9d80f3e

**Comment by theincognito-inc** [comment]
@ExodusHour 4.1.6 is too old. Try one thing - Completely uninstall (purge) ffmpeg from the pi. Then download the release build (4.3.1), according to your architecture from here: https://johnvansickle.com/ffmpeg/

These are static ffmpeg builds. So you just need to extract the zip and add the ffmpeg folder to your path.

**Comment by ExodusHour** [comment]
@theincognito-inc It's working now, thank you! I'm not sure why ffmpeg wasn't updating but I uninstalled it and added a static version, thanks for helping!
