### ISSUE TITLE
[Broken] ERROR: Unable to extract ytInitialData

### ISSUE THREAD

**Issue by harroguk** [blackjack4494/yt-dlc#266]
## Checklist

- [/] I'm reporting a broken site support
- [/] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [/] I've checked that all provided URLs are alive and playable in a browser
- [/] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [/] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-j', '--flat-playlist', '--cookies', 'D:\\scripts\\Powershell\\youtube-dl\\cookies.txt', '--playlist-end', '20', '--write-all-thumbnails', '--format', 'bestvideo[ext=mp4][vcodec!*=av01]+bestaudio[ex
t=m4a]', '--yes-playlist', '--add-metadata', '--ignore-errors', '--match-filter', '!is_live | duration < 3600', '--no-overwrites', '--mark-watched', '--download-archive', 'D:\\scripts\\Powershell\\youtube-dl\\YouTube-Downloaded.log', '--out
put', 'D:\\TV\\YouTube\\%(uploader)s [%(channel_id)s]\\%(uploader)s - s2020e1113014%(playlist_index)s - %(title)s  [%(id)s].%(ext)s', 'https://www.youtube.com/feed/subscriptions']
[debug] Loading archive file 'D:\\scripts\\Powershell\\youtube-dl\\YouTube-Downloaded.log'
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.3 (CPython) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: ffmpeg git-2020-06-03-b6d7c4c, ffprobe git-2020-06-03-b6d7c4c
[debug] Proxy map: {}
ERROR: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtub
e-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\installedprograms\python38\lib\site-packages\youtube_dlc\YoutubeDL.py", line 846, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\installedprograms\python38\lib\site-packages\youtube_dlc\YoutubeDL.py", line 1006, in process_ie_result
    entries = list(itertools.islice(
  File "c:\installedprograms\python38\lib\site-packages\youtube_dlc\extractor\youtube.py", line 341, in _entries
    data_json = self._parse_json(self._search_regex(self._INITIAL_DATA_RE, page, 'ytInitialData'), None)
  File "c:\installedprograms\python38\lib\site-packages\youtube_dlc\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dlc.utils.RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to
 update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Unable to extract the subscription playlist.
I have attempted updating cookies

**Comment by harroguk** [comment]
When I said I updated the cookies, I only updated the youtube.com cookies, seems if I update "All Cookies" it works. I guess it is referencing some google cookies somewhere too.
