### ISSUE TITLE
[Broken] Archive.org + playlists

### ISSUE THREAD

**Issue by blackjack4494** [blackjack4494/yt-dlc#269]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

Playlist error output
```
[archive.org] WeihnachtenBeiHoppenstedts: Downloading webpage
ERROR: Unable to extract jwplayer playlist; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.Traceback (most recent call last):
  File "D:\gitkraken\yt-dlc\youtube_dlc\YoutubeDL.py", line 849, in wrapper
  File "D:\gitkraken\yt-dlc\youtube_dlc\YoutubeDL.py", line 870, in __extract_info
    ie_result = ie.extract(url)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\archiveorg.py", line 45, in _real_extract
    webpage, 'jwplayer playlist'), video_id)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dlc.utils.RegexNotFoundError: Unable to extract jwplayer playlist; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

Specific video
```
[generic] Weihnachten+bei+Hoppenstedts: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Weihnachten+bei+Hoppenstedts: Downloading webpage
Traceback (most recent call last):
  File "D:\gitkraken\yt-dlc\youtube_dlc\YoutubeDL.py", line 849, in wrapper
    return func(self, *args, **kwargs)
  File "D:\gitkraken\yt-dlc\youtube_dlc\YoutubeDL.py", line 870, in __extract_info
    ie_result = ie.extract(url)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "D:\gitkraken\yt-dlc\youtube_dlc\extractor\generic.py", line 3400, in _real_extract
    raise UnsupportedError(url)
youtube_dlc.utils.UnsupportedError: Unsupported URL: https://archive.org/details/WeihnachtenBeiHoppenstedts/Weihnachten+bei+Hoppenstedts.mp4
```

## Description

https://archive.org/details/WeihnachtenBeiHoppenstedts  
or  
https://archive.org/details/WeihnachtenBeiHoppenstedts/Weihnachten+bei+Hoppenstedts.mp4  
will result in errors.

There have been some related issues
ytdl-org/youtube-dl#27236
ytdl-org/youtube-dl#27109
ytdl-org/youtube-dl#26780
ytdl-org/youtube-dl#25466
ytdl-org/youtube-dl#25277
ytdl-org/youtube-dl#23946
ytdl-org/youtube-dl#23700
ytdl-org/youtube-dl#23586
ytdl-org/youtube-dl#21330
ytdl-org/youtube-dl#7154

Some proposed patches
ytdl-org/youtube-dl#27156
ytdl-org/youtube-dl#23827

`--force-generic` won't work.  
I think this extractor should get some attention as archive.org is well known and got lots of stuff. However you are able to download everything fine when browsing there. But still some people may prefer to use a command-line tool or want to embedded it into their (gui) projects.

**Comment by october262** [comment]
this link - https://archive.org/serve/WeihnachtenBeiHoppenstedts/Weihnachten%20bei%20Hoppenstedts.mp4   works, just open the debug menu - select network - media, copy the first URL

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/pull/27156
