### ISSUE TITLE
NBC Broke?

### ISSUE THREAD

**Issue by jriker1** [blackjack4494/yt-dlc#286]
Running version 2002.11.11-3 in Windows of Youtube-dlc.  Tried downloading Saturday Night Live like I have many times in the past and received an error.  The call is:

youtube-dlc --audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username ##### --ap-password ##### https://www.nbc.com/saturday-night-live/video/december-19-kristen-wiig/4280686 -o "Saturday Night Live S46E9.mp4"

Error is:

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/saturday-night-live/video/december-19-kristen-wiig/4280686', '-o', 'Saturday Night Live S46E9.mp4', '--verbose']
> [debug] Loading archive file None
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] youtube-dlc version 2020.11.11-3
> [debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
> [debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
> [debug] Proxy map: {}
> [NBC] 4280686: Downloading JSON metadata
> Traceback (most recent call last):
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\Scripts\youtube-dlc.exe\__main__.py", line 7, in <module>
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\__init__.py", line 487, in main
>     _real_main(argv)
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\__init__.py", line 477, in _real_main
>     retcode = ydl.download(all_urls)
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2103, in download
>     res = self.extract_info(
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
>     ie_result = ie.extract(url)
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
>     ie_result = self._real_extract(url)
>   File "c:\users\jriker\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\nbc.py", line 135, in _real_extract
>     video_id = video_data['mpxGuid']
> TypeError: 'NoneType' object is not subscriptable

**Comment by october262** [comment]
no need to use the username & password.
just use youtube-dlc  https://www.nbc.com/saturday-night-live/video/december-19-kristen-wiig/4280686  the show will download

**Comment by merval** [comment]
the command your using works for me in 2020.11.11-2. I tried both ap-mso and netrc. Reading the stack you provided, it's failing to find anything for the video_id. What's interesting though is the fact you're not getting an authentication error, but you're getting a TypeError.

What I suspect happened, is when you made the request, their back-end server didn't respond correctly and you were left with a bad response.
