### ISSUE TITLE
[Broken] FXNOW ? 

### ISSUE THREAD

**Issue by jschwalbe** [blackjack4494/yt-dlc#293]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running youtube-dlc version **2020.10.31** <-- actually 2020.11.11-2 _(seems this template is old)_
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dlc -v --ap-mso DTV --ap-username <snipped> --ap-password <snipped> https://fxnow.fxnetworks.com/movies-and-specials/jumanji-welcome-to-the-jungle
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://fxnow.fxnetworks.com/movies-and-specials/jumanji-welcome-to-the-jungle']
[debug] Loading archive file None
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dlc version 2020.11.11-2
[debug] Python version 3.6.0 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] jumanji-welcome-to-the-jungle: Requesting header
WARNING: Falling back on generic information extractor.
[generic] jumanji-welcome-to-the-jungle: Downloading webpage
[generic] jumanji-welcome-to-the-jungle: Extracting information
WARNING: [generic] jumanji-welcome-to-the-jungle: Failed to parse JSON Expecting value: line 6 column 27 (char 181)
ERROR: Unsupported URL: https://fxnow.fxnetworks.com/movies-and-specials/jumanji-welcome-to-the-jungle
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dlc/YoutubeDL.py", line 849, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dlc/YoutubeDL.py", line 870, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/youtube_dlc/extractor/generic.py", line 3400, in _real_extract
    raise UnsupportedError(url)
```

## Description

Can't seem to get this to work. 
- I also tried watching the source files, there is a .mpd file, which I'm unable to make work. 
- There's also a .m3u file referenced in the sources: https://content.uplynk.com/e49201b37fd84f86a855465c08533598.m3u8 - I tried this but got tons of `SAMPLE-AES encryption is not supported yet` errors. 

Would love to be able to watch this on the airplane! Thanks

**Comment by pukkandan** [comment]
It looks like it has DRM. yt-dlc doesn't support content with DRM
