### ISSUE TITLE
CBS Broke?

### ISSUE THREAD

**Issue by jriker1** [blackjack4494/yt-dlc#295]
On latest version on Windows and started having issues with CBS.  Below is the verbose output.  Any thoughts?  Been like this for a few days:

`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.cbs.com/shows/the_bold_and_the_beautiful/video/PSReSU5U_0nbb4E2zM6UaeZaJSgO7sQ1/the-bold-and-the-beautiful-12-31-2020/', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[CBS] PSReSU5U_0nbb4E2zM6UaeZaJSgO7sQ1: Downloading XML
ERROR: No video formats found; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\cbs.py", line 112, in _real_extract
    return self._extract_video_info(content_id)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\cbs.py", line 94, in _extract_video_info
    self._sort_formats(formats)
  File "c:\users\appdata\local\programs\python\python39\lib\site-packages\youtube_dlc\extractor\common.py", line 1359, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dlc.utils.ExtractorError: No video formats found; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.`

**Comment by keith-leitch** [comment]
I tried the B&B URL you attempted above. It failed, but I got exactly the same behavior that I get with the problems reported in https://github.com/blackjack4494/yt-dlc/issues/275#issuecomment-748514188 . What are you seeing that is different?

I can't seem to make CBS fail with any other show that isn't noted in https://github.com/blackjack4494/yt-dlc/issues/275#issuecomment-748514188 (e.g. NCIS or The Unicorn). Let's see what happens with new episodes, after the holiday hiatus.

**Comment by jriker1** [comment]
Why do you think they are the same?  The other one says 

Could not find XML element title

This one says:

No video formats found

**Comment by keith-leitch** [comment]
Ah, sorry. You are right. The B&B example does not display "Could not find XML element title" while the others do. Sorry I missed that the first time.

However, they both tell me before bailing that "No video formats are found." 

I could, indeed, be a different issue.

**Comment by keith-leitch** [comment]
Here's another thought that might not be useful: B&B is a daily, while everything else I've tried is from a weekly or a one-off broadcast. Is it possible that they are only posting one format for the soaps, and therefore no list? I'm not pretending to know that is common practice, or anything: just spitballing. Have you downloaded previous episodes successfully?

**Comment by jriker1** [comment]
Yep, been downloading it for months.  As a matter of fact Young and the Restless on the same channel works fine.
