### ISSUE TITLE
NoneType Object has no attribute 'get' Error

### ISSUE THREAD

**Issue by Finnlife** [blackjack4494/yt-dlc#305]
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.11.11-3**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

(hbzdownloader) root@Hauptserver:/home/hbzdownloader# youtube-dlc --verbose https://www.youtube.com/watch?v=LczRvzIXg_o
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=LczRvzIXg_o']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.9.1 (CPython) - Linux-4.19.0-12-amd64-x86_64-with-glibc2.28
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube] LczRvzIXg_o: Downloading webpage
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/bin/youtube-dlc", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/lib/python3.9/site-packages/youtube_dlc/__init__.py", line 487, in main
    _real_main(argv)
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/lib/python3.9/site-packages/youtube_dlc/__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/lib/python3.9/site-packages/youtube_dlc/YoutubeDL.py", line 2103, in download
    res = self.extract_info(
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/lib/python3.9/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/lib/python3.9/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/root/.local/share/virtualenvs/hbzdownloader-WRrlBKKW/lib/python3.9/site-packages/youtube_dlc/extractor/youtube.py", line 1940, in _real_extract
    args = ytplayer_config.get("args")
AttributeError: 'NoneType' object has no attribute 'get'

## Description

I've tried to download this Video with de yt-dlc but there is an Error as you can see ^^

**Comment by pukkandan** [comment]
Blackjack has not been seen from for over 3 months now. You can try out my fork [yt-dlp](https://github.com/pukkandan/yt-dlp)

**Comment by Finnlife** [comment]
Thank you for you're response @pukkandan
