### ISSUE TITLE
Unable to extract ytInitialData

### ISSUE THREAD

**Issue by mansj** [blackjack4494/yt-dlc#307]
Hi, I've updated to the latest version (using pip) but I'm still getting this error:

```
youtube-dlc --verbose https://www.youtube.com/playlist?list=XXXXX- -o "XXXX"

[debug] System config: []

[debug] User config: []

[debug] Custom config: []

[debug] Loading archive file None

[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8

[debug] youtube-dlc version 2020.11.11-3

[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-14-686-pae-i686-with-debian-10.9

[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs ., rtmpdump 2.4

[debug] Proxy map: {}

[youtube:playlist] PLoSytarswoSPP06AYmdN2bKT1U9HZkQ4-: Downloading webpage

ERROR: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

Traceback (most recent call last):

  File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info

    ie_result = ie.extract(url)

  File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/common.py", line 532, in extract

    ie_result = self._real_extract(url)

  File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/youtube.py", line 3042, in _real_extract

    has_videos, playlist = self._extract_playlist(playlist_id)

  File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/youtube.py", line 2994, in _extract_playlist

    next(self._entries(page, playlist_id))

  File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/youtube.py", line 341, in _entries

    data_json = self._parse_json(self._search_regex(self._INITIAL_DATA_RE, page, 'ytInitialData'), None)

  File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/common.py", line 1010, in _search_regex

    raise RegexNotFoundError('Unable to extract %s' % _name)

RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
This project has not had any updates for half an year. You can check out my fork [yt-dlp](https://github.com/yt-dlp/yt-dlp)

**Comment by mansj** [comment]
Thank you.

**Comment by alexi28baez** [comment]
> Hola, he actualizado a la última versión (usando pip) pero todavía recibo este error:
> 
> ```
> youtube-dlc --verbose https://www.youtube.com/playlist?list=XXXXX- -o "XXXX"
> 
> [debug] System config: []
> 
> [debug] User config: []
> 
> [debug] Custom config: []
> 
> [debug] Loading archive file None
> 
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> 
> [debug] youtube-dlc version 2020.11.11-3
> 
> [debug] Python version 2.7.16 (CPython) - Linux-4.19.0-14-686-pae-i686-with-debian-10.9
> 
> [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs ., rtmpdump 2.4
> 
> [debug] Proxy map: {}
> 
> [youtube:playlist] PLoSytarswoSPP06AYmdN2bKT1U9HZkQ4-: Downloading webpage
> 
> ERROR: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
> 
> Traceback (most recent call last):
> 
>   File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
> 
>     ie_result = ie.extract(url)
> 
>   File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
> 
>     ie_result = self._real_extract(url)
> 
>   File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/youtube.py", line 3042, in _real_extract
> 
>     has_videos, playlist = self._extract_playlist(playlist_id)
> 
>   File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/youtube.py", line 2994, in _extract_playlist
> 
>     next(self._entries(page, playlist_id))
> 
>   File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/youtube.py", line 341, in _entries
> 
>     data_json = self._parse_json(self._search_regex(self._INITIAL_DATA_RE, page, 'ytInitialData'), None)
> 
>   File "/home/manjo/.local/lib/python2.7/site-packages/youtube_dlc/extractor/common.py", line 1010, in _search_regex
> 
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> 
> RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
> ```

Hola se puede arreglar el error?
