### ISSUE TITLE
Strange Bug while trying List video formats

### ISSUE THREAD

**Issue by SpodeMaster** [blackjack4494/yt-dlc#308]
L:\other youtube>youtube-dlc.exe -F https://youtu.be/7J4_pfLQlac
[youtube] 7J4_pfLQlac: Downloading webpage
[youtube] 7J4_pfLQlac: Downloading embed webpage
Traceback (most recent call last):
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\colosus\AppData\Local\Programs\Python\Python38\Scripts\youtube-dlc.exe\__main__.py", line 7, in <module>
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\site-packages\youtube_dlc\__init__.py", line 487, in main
    _real_main(argv)
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\site-packages\youtube_dlc\__init__.py", line 477, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\site-packages\youtube_dlc\YoutubeDL.py", line 2103, in download
    res = self.extract_info(
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\site-packages\youtube_dlc\YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\site-packages\youtube_dlc\extractor\common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\site-packages\youtube_dlc\extractor\youtube.py", line 1873, in _real_extract
    playable_in_embed = re.search(r'{\\\"playableInEmbed\\\":(?P<playableinEmbed>[^\,]+)', ext)
  File "c:\users\colosus\appdata\local\programs\python\python38\lib\re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by llacb47** [comment]
This project is abandoned, use https://github.com/yt-dlp/yt-dlp
