### ISSUE TITLE
Unable to --embed-thumbnail when downloading from Mixcloud.

### ISSUE THREAD

**Issue by JeffreyShran** [blackjack4494/yt-dlc#309]
## Checklist

- [X ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running youtube-dlc version **2020.10.31**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
jeff@LIAN-LI:/mnt/c/Users/d/Downloads/music$ youtube-dlc --add-metadata --embed-thumbnail https://www.mixcloud.com/Dizzyuk/dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294/
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading JSON metadata
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading m3u8 information
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading MPD manifest
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading thumbnail ...
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Writing thumbnail to: DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.jpg
[download] Destination: DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a
[download] 100% of 22.43MiB in 00:02
[ffmpeg] Adding metadata to 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a'
[atomicparsley] Adding thumbnail to "DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a"
ERROR:
jeff@LIAN-LI:/mnt/c/Users/d/Downloads/music$ youtube-dlc -v --add-metadata --embed-thumbnail https://www.mixcloud.com/Dizzyuk/dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--add-metadata', '--embed-thumbnail', 'https://www.mixcloud.com/Dizzyuk/dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.8.10 (CPython) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading JSON metadata
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading m3u8 information
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Downloading thumbnail ...
[mixcloud] Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294: Writing thumbnail to: DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.jpg
[debug] Invoking downloader on 'https://stream7.mixcloud.com/secure/c/m4a/64/8/2/8/0/0158-622f-4bb1-a601-9acdc447daeb.m4a?sig=fXz4AUO7QDbkSvY_FjdLIw'
[download] Destination: DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a
[download] 100% of 22.43MiB in 00:02
[ffmpeg] Adding metadata to 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a' -map 0 -vn -acodec copy -metadata 'title=DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94' -metadata date=20201208 -metadata 'description=DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94' -metadata 'comment=DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94' -metadata purl=https://www.mixcloud.com/Dizzyuk/dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294/ -metadata 'artist=Vibes & Wishdokta, Edit V, Dj Ham, Q Project' 'file:DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.temp.m4a'
[atomicparsley] Adding thumbnail to "DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a"
[debug] AtomicParsley command line: AtomicParsley 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.m4a' --artwork 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.jpg' -o 'DJ Grooverider - United Dance Impact Records Showcase - Stevenage Arts & Leisure Centre - 02.12.94-Dizzyuk_dj-grooverider-united-dance-impact-records-showcase-stevenage-arts-leisure-centre-021294.temp.m4a'
ERROR:
Traceback (most recent call last):
  File "/home/jeff/.local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 2150, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/jeff/.local/lib/python3.8/site-packages/youtube_dlc/postprocessor/embedthumbnail.py", line 131, in run
    raise EmbedThumbnailPPError(msg)
youtube_dlc.postprocessor.embedthumbnail.EmbedThumbnailPPError

jeff@LIAN-LI:/mnt/c/Users/d/Downloads/music$ youtube-dlc --version
2020.11.11-3
```

## Description

Unable to get thumbnails to work when downloading from Mixcloud. There is no error, but I've added the stack trace.

**Comment by october262** [comment]
yt-dlc has possibly been abandoned, use either youtube-dl  - https://github.com/ytdl-org/youtube-dl or yt-dlp - https://github.com/yt-dlp/yt-dlp
