### ISSUE TITLE
[Broken] Bandcamp again.

### ISSUE THREAD

**Issue by nicolaasjan** [blackjack4494/yt-dlc#31]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
youtube-dlc -v https://artikalmusic.bandcamp.com/album/far-north-dubs-ep
[debug] System config: []
[debug] User config: ['-o', '/dev/shm/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://artikalmusic.bandcamp.com/album/far-north-dubs-ep']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-122-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-99430-g9d8f9b2-Nico_20201001, ffprobe N-99430-g9d8f9b2-Nico_20201001
[debug] Proxy map: {}
[Bandcamp:album] far-north-dubs-ep: Downloading webpage
ERROR: The page doesn't contain any tracks; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/bandcamp.py", line 311, in _real_extract
    raise ExtractorError('The page doesn\'t contain any tracks')
youtube_dlc.utils.ExtractorError: The page doesn't contain any tracks; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

As a user on Reddit [experienced](https://old.reddit.com/r/youtubedl/comments/j0avwd/downloading_bandcamp_albums_not_working/ga9a5ek/), Bandcamp stopped working again.
Doesn't matter what album.

**Comment by blackjack4494** [comment]
I believe there was a PR just a day or so before the DMCA hit.

**Comment by nicolaasjan** [comment]
> I believe there was a PR just a day or so before the DMCA hit.

Is the PR now gone forever, or might there be a way to dig it up somewhere?
Aren't these also on your local machine?
Sorry, I'm a git noob. ;)

**Comment by adrianheine** [comment]
I guess that would be animelover1984/youtube-dl@955906045fdd24b21a9b6edd8c410d36394f7241 (PR 26684) by @gilou

**Comment by nicolaasjan** [comment]
I can confirm that the pull request of @insaneracist works.

```
youtube-dlc -v https://artikalmusic.bandcamp.com/album/far-north-dubs-ep
[debug] System config: []
[debug] User config: ['-o', '/dev/shm/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--embed-thumbnail']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://artikalmusic.bandcamp.com/album/far-north-dubs-ep']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.28
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-122-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-99430-g9d8f9b2-Nico_20201001, ffprobe N-99430-g9d8f9b2-Nico_20201001
[debug] Proxy map: {}
[Bandcamp:album] far-north-dubs-ep: Downloading webpage
[download] Downloading playlist: Far North Dubs EP
[Bandcamp:album] playlist Far North Dubs EP: Collected 4 video ids (downloading 4 of them)
[download] Downloading video 1 of 4
[Bandcamp:albumtrack] the-14th: Downloading webpage
[Bandcamp:albumtrack] 38607395: Downloading thumbnail ...
[Bandcamp:albumtrack] 38607395: Writing thumbnail to: /dev/shm/01 - Ternion Sound - The 14th.jpg
[debug] Invoking downloader on 'https://t4.bcbits.com/stream/0276f504508083c8af479394d846ef4b/mp3-128/38607395?p=0&ts=1603960961&t=5709604a8b1ac657281e5d47f7b700d767f0b860&token=1603960961_733522d06f6295c63f64ed69ffcf10a27c43d2bc'
[download] Destination: /dev/shm/01 - Ternion Sound - The 14th.mp3
[download] 100% of 5.94MiB in 00:01
[ffmpeg] Adding metadata to '/dev/shm/01 - Ternion Sound - The 14th.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/01 - Ternion Sound - The 14th.mp3' -map 0 -c copy -metadata 'title=The 14th' -metadata date=20201001 -metadata purl=https://artikalmusic.bandcamp.com/track/the-14th -metadata track=1 -metadata 'artist=Ternion Sound' -metadata 'album=Far North Dubs EP' 'file:/dev/shm/01 - Ternion Sound - The 14th.temp.mp3'
[ffmpeg] Adding thumbnail to "/dev/shm/01 - Ternion Sound - The 14th.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/01 - Ternion Sound - The 14th.mp3' -i 'file:/dev/shm/01 - Ternion Sound - The 14th.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:/dev/shm/01 - Ternion Sound - The 14th.temp.mp3'
[download] Downloading video 2 of 4
[Bandcamp:albumtrack] parasite-vip: Downloading webpage
[Bandcamp:albumtrack] 2197259922: Downloading thumbnail ...
[Bandcamp:albumtrack] 2197259922: Writing thumbnail to: /dev/shm/02 - Ternion Sound - Parasite VIP.jpg
[debug] Invoking downloader on 'https://t4.bcbits.com/stream/c46ca6ff4fc3009c4bed1b8ce8189b74/mp3-128/2197259922?p=0&ts=1603960964&t=26125c556fe70d6ddff4ffb654db7ece35dd953e&token=1603960964_9430e5bf3ab30e30870fca2d457907faab19eeb0'
[download] Destination: /dev/shm/02 - Ternion Sound - Parasite VIP.mp3
[download] 100% of 2.54MiB in 00:00
[ffmpeg] Adding metadata to '/dev/shm/02 - Ternion Sound - Parasite VIP.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/02 - Ternion Sound - Parasite VIP.mp3' -map 0 -c copy -metadata 'title=Parasite VIP' -metadata date=20201001 -metadata purl=https://artikalmusic.bandcamp.com/track/parasite-vip -metadata track=2 -metadata 'artist=Ternion Sound' -metadata 'album=Far North Dubs EP' 'file:/dev/shm/02 - Ternion Sound - Parasite VIP.temp.mp3'
[ffmpeg] Adding thumbnail to "/dev/shm/02 - Ternion Sound - Parasite VIP.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/02 - Ternion Sound - Parasite VIP.mp3' -i 'file:/dev/shm/02 - Ternion Sound - Parasite VIP.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:/dev/shm/02 - Ternion Sound - Parasite VIP.temp.mp3'
[download] Downloading video 3 of 4
[Bandcamp:albumtrack] smoke-em-out: Downloading webpage
[Bandcamp:albumtrack] 517298133: Downloading thumbnail ...
[Bandcamp:albumtrack] 517298133: Writing thumbnail to: /dev/shm/03 - Ternion Sound - Smoke Em Out.jpg
[debug] Invoking downloader on 'https://t4.bcbits.com/stream/830b5a75235f96ae0604a848eb404cc5/mp3-128/517298133?p=0&ts=1603960965&t=debc95d64710e5000b19f75b44730097e27f68e8&token=1603960965_56dfbd45e21a6fa96701c2f075731e5754135413'
[download] Destination: /dev/shm/03 - Ternion Sound - Smoke Em Out.mp3
[download] 100% of 4.60MiB in 00:00
[ffmpeg] Adding metadata to '/dev/shm/03 - Ternion Sound - Smoke Em Out.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/03 - Ternion Sound - Smoke Em Out.mp3' -map 0 -c copy -metadata 'title=Smoke Em Out' -metadata date=20201001 -metadata purl=https://artikalmusic.bandcamp.com/track/smoke-em-out -metadata track=3 -metadata 'artist=Ternion Sound' -metadata 'album=Far North Dubs EP' 'file:/dev/shm/03 - Ternion Sound - Smoke Em Out.temp.mp3'
[ffmpeg] Adding thumbnail to "/dev/shm/03 - Ternion Sound - Smoke Em Out.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/03 - Ternion Sound - Smoke Em Out.mp3' -i 'file:/dev/shm/03 - Ternion Sound - Smoke Em Out.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:/dev/shm/03 - Ternion Sound - Smoke Em Out.temp.mp3'
[download] Downloading video 4 of 4
[Bandcamp:albumtrack] far-north-dub: Downloading webpage
[Bandcamp:albumtrack] 795161796: Downloading thumbnail ...
[Bandcamp:albumtrack] 795161796: Writing thumbnail to: /dev/shm/04 - Ternion Sound - Far North Dub.jpg
[debug] Invoking downloader on 'https://t4.bcbits.com/stream/a331b69c2c7523e1f88a82611b00a85c/mp3-128/795161796?p=0&ts=1603960967&t=a65d6f1861723dac893f9b39188b3dd221932e2a&token=1603960967_c634053633fdd9fcfbaf174d1a0bdc42f4fdd185'
[download] Destination: /dev/shm/04 - Ternion Sound - Far North Dub.mp3
[download] 100% of 3.56MiB in 00:00
[ffmpeg] Adding metadata to '/dev/shm/04 - Ternion Sound - Far North Dub.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/04 - Ternion Sound - Far North Dub.mp3' -map 0 -c copy -metadata 'title=Far North Dub' -metadata date=20201001 -metadata purl=https://artikalmusic.bandcamp.com/track/far-north-dub -metadata track=4 -metadata 'artist=Ternion Sound' -metadata 'album=Far North Dubs EP' 'file:/dev/shm/04 - Ternion Sound - Far North Dub.temp.mp3'
[ffmpeg] Adding thumbnail to "/dev/shm/04 - Ternion Sound - Far North Dub.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/04 - Ternion Sound - Far North Dub.mp3' -i 'file:/dev/shm/04 - Ternion Sound - Far North Dub.jpg' -c copy -map 0 -map 1 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (Front)"' 'file:/dev/shm/04 - Ternion Sound - Far North Dub.temp.mp3'
[download] Finished downloading playlist: Far North Dubs EP
```
