### ISSUE TITLE
Some downloads fail with KeyError: 'url'

### ISSUE THREAD

**Issue by jbruchon** [blackjack4494/yt-dlc#42]
## Verbose log

```
Y:\YouTube Channels\NonCompete>youtube-dl --cookies "Y:\cookies.txt" --add-metadata --write-description --write-info-json --write-thumbnail --download-archive "Y:\ytdl_archive.txt" --all-subs --sleep-interval 1 -ciw -o "%(title)s.%(ext)s" -v https://www.youtube.com/channel/UCkZFKKK-0YB0FvwoS8P7nHg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'Y:\\cookies.txt', '--add-metadata', '--write-description', '--write-info-json', '--write-thumbnail', '--download-archive', 'Y:\\ytdl_archive.txt', '--all-subs', '--sleep-interval', '1', '-ciw', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/channel/UCkZFKKK-0YB0FvwoS8P7nHg']
[debug] Loading archive file 'Y:\\ytdl_archive.txt'
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.26
[debug] Python version 3.8.6 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-15-51db0a4, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:channel] UCkZFKKK-0YB0FvwoS8P7nHg: Downloading channel page
[youtube:playlist] UUkZFKKK-0YB0FvwoS8P7nHg: Downloading webpage
[download] Downloading playlist: Uploads from NonCompete
[youtube:playlist] UUkZFKKK-0YB0FvwoS8P7nHg: Downloading page #1
[youtube:playlist] playlist Uploads from NonCompete: Downloading 159 videos
[download] Downloading video 1 of 159
[youtube] T78IcPvnBtQ: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Video description is already present
[info] Writing video subtitles to: Viva South America! El Breadcast!.live_chat.json
ERROR: 'url'
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 841, in extract_info
  File "youtube_dlc\YoutubeDL.py", line 896, in process_ie_result
  File "youtube_dlc\YoutubeDL.py", line 1691, in process_video_result
  File "youtube_dlc\YoutubeDL.py", line 1893, in process_info
KeyError: 'url'
```

## Description

For some videos, I'm seeing failures with `KeyError: 'url'` (and this time I've actually confirmed the videos work on the site). This is with the latest release version.

**Comment by blackjack4494** [comment]
`all-subs` related.

**Comment by im-coooding** [comment]
This seems to be caused by the change that disables sleep interval for subtitles. As such, enabling `--sleep-subtitles` makes it work again and I can download videos along with the live chat and other subtitles just fine.

When `--sleep-subtitles` is on it uses the dl function to download, which in turn chooses the correct handler for live chats. Without it, it seems to use some new code that tries to directly download the subtitles instead, which breaks:

At line 1894 in YoutubeDL.py:
```
                            if self.params.get('sleep_interval_subtitles', False):
                                dl(sub_filename, sub_info) <---------- This works fine
                            else:
                                sub_data = ie._request_webpage(
                                    sub_info['url'], info_dict['id'], note=False).read() <---- This breaks at sub_info['url']
                                with io.open(encodeFilename(sub_filename), 'wb') as subfile:
                                    subfile.write(sub_data)
```

It seems the correct thing to do would be to use the dl function in both cases, but temporarily disable (or just set to zero) the sleep interval while the function is called. Something like that at least.

I'm not familiar enough with the code to make a patch myself, but hopefully this helps. At least there's workaround for those who need it!

**Comment by blackjack4494** [comment]
@im-coooding that is actually quite interesting that you mention it. I will revert current effort to deactivate live_chat and pass along some default value of 0 for sleep interval for subtitles.
