### ISSUE TITLE
[Broken] ERROR: Unable to extract JS player URL

### ISSUE THREAD

**Issue by bodqhrohro** [blackjack4494/yt-dlc#48]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
@bq:03:11:27:/tmp/dl$ youtube-dlc --verbose -F https://www.youtube.com/watch?v=hKAB91trmbg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=hKAB91trmbg']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.26
[debug] Python version 2.7.18 (CPython) - Linux-5.8.0-3-amd64-x86_64-with-debian-bullseye-sid
[debug] exe versions: avconv 4.3.1-3, avprobe 4.3.1-3, ffmpeg 4.3.1-3, ffprobe 4.3.1-3, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] hKAB91trmbg: Downloading webpage
[youtube] hKAB91trmbg: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 1966, in _real_extract
    yt_initial_data['contents']['twoColumnWatchNextResults']['conversationBar']['liveChatRenderer']['continuations'][0]['reloadContinuationData']['continuation']
KeyError: u'conversationBar'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 2066, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

**Comment by makeworld-the-better-one** [comment]
No problem on Python 3 on Arch Linux.
```
❯ youtube-dlc --verbose -F https://www.youtube.com/watch\?v\=hKAB91trmbg
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-F', 'https://www.youtube.com/watch?v=hKAB91trmbg']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dlc version 2020.10.25
[debug] Python version 3.8.6 (CPython) - Linux-5.8.14-arch1-1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] hKAB91trmbg: Downloading webpage
[youtube] hKAB91trmbg: Downloading embed webpage
[youtube] {18} signature length 105, html5 player 9b65e980
[youtube] hKAB91trmbg: Downloading player https://www.youtube.com/s/player/9b65e980/player_ias.vflset/en_US/base.js
[youtube] {137} signature length 109, html5 player 9b65e980
[youtube] hKAB91trmbg: Downloading player https://www.youtube.com/s/player/9b65e980/player_ias.vflset/en_US/base.js
[youtube] {248} signature length 109, html5 player 9b65e980
[youtube] {399} signature length 109, html5 player 9b65e980
[youtube] {136} signature length 109, html5 player 9b65e980
[youtube] {247} signature length 109, html5 player 9b65e980
[youtube] {398} signature length 109, html5 player 9b65e980
[youtube] {135} signature length 109, html5 player 9b65e980
[youtube] {244} signature length 109, html5 player 9b65e980
[youtube] {397} signature length 109, html5 player 9b65e980
[youtube] {134} signature length 105, html5 player 9b65e980
[youtube] {243} signature length 109, html5 player 9b65e980
[youtube] {396} signature length 109, html5 player 9b65e980
[youtube] {133} signature length 109, html5 player 9b65e980
[youtube] {242} signature length 105, html5 player 9b65e980
[youtube] {395} signature length 109, html5 player 9b65e980
[youtube] {160} signature length 109, html5 player 9b65e980
[youtube] {278} signature length 109, html5 player 9b65e980
[youtube] {394} signature length 109, html5 player 9b65e980
[youtube] {140} signature length 105, html5 player 9b65e980
[youtube] {249} signature length 105, html5 player 9b65e980
[youtube] {250} signature length 105, html5 player 9b65e980
[youtube] {251} signature length 105, html5 player 9b65e980
[info] Available formats for hKAB91trmbg:
format code  extension  resolution note
249          webm       audio only tiny   55k , opus @ 50k (48000Hz), 1.06MiB
250          webm       audio only tiny   72k , opus @ 70k (48000Hz), 1.40MiB
140          m4a        audio only tiny  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.86MiB
251          webm       audio only tiny  136k , opus @160k (48000Hz), 2.79MiB
160          mp4        256x144    144p   18k , avc1.4d400b, 15fps, video only, 346.72KiB
133          mp4        426x240    240p   31k , avc1.4d4015, 15fps, video only, 579.85KiB
394          mp4        256x144    144p   56k , av01.0.00M.08, 15fps, video only, 1.00MiB
395          mp4        426x240    240p   71k , av01.0.00M.08, 15fps, video only, 1.37MiB
278          webm       256x144    144p   90k , webm container, vp9, 15fps, video only, 875.52KiB
396          mp4        640x360    360p  121k , av01.0.01M.08, 15fps, video only, 2.23MiB
242          webm       426x240    240p  124k , vp9, 15fps, video only, 1.75MiB
134          mp4        640x360    360p  146k , avc1.4d4016, 15fps, video only, 1.16MiB
397          mp4        854x480    480p  201k , av01.0.04M.08, 15fps, video only, 3.39MiB
243          webm       640x360    360p  219k , vp9, 15fps, video only, 3.00MiB
135          mp4        854x480    480p  304k , avc1.4d401e, 15fps, video only, 1.96MiB
244          webm       854x480    480p  335k , vp9, 15fps, video only, 3.10MiB
398          mp4        1280x720   720p  414k , av01.0.05M.08, 15fps, video only, 7.44MiB
247          webm       1280x720   720p  620k , vp9, 15fps, video only, 7.76MiB
136          mp4        1280x720   720p  674k , avc1.4d401f, 15fps, video only, 3.30MiB
399          mp4        1920x1080  1080p  704k , av01.0.08M.08, 15fps, video only, 12.92MiB
248          webm       1920x1080  1080p 1074k , vp9, 15fps, video only, 12.69MiB
137          mp4        1920x1080  1080p 1419k , avc1.640028, 15fps, video only, 5.30MiB
18           mp4        640x360    360p  307k , avc1.42001E, 15fps, mp4a.40.2@ 96k (44100Hz), 6.92MiB (best)
```

But on Python 2 on Debian...

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-F', u'https://www.youtube.com/watch?v=hKAB91trmbg']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.26
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube] hKAB91trmbg: Downloading webpage
[youtube] hKAB91trmbg: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 1966, in _real_extract
    yt_initial_data['contents']['twoColumnWatchNextResults']['conversationBar']['liveChatRenderer']['continuations'][0]['reloadContinuationData']['continuation']
KeyError: u'conversationBar'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 2066, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

Strange.

**Comment by makeworld-the-better-one** [comment]
It seemed to work with 2020.10.25. Just not .26.

**Comment by makeworld-the-better-one** [comment]
This command alternates between working and not working when I run it repeatedly.

**Comment by blackjack4494** [comment]
search before posting.
