### ISSUE TITLE
[Broken] Youtube download not working

### ISSUE THREAD

**Issue by IdreesM0** [blackjack4494/yt-dlc#53]
## Checklist

- [ x] I'm reporting a broken site support
- [ x] I've verified that I'm running youtube-dlc version **2020.10.26**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=HRHVJPFKCqE']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.26
[debug] Python version 2.7.18 (CPython) - Linux-5.4.0-52-generic-x86_64-with-Ubuntu-20.04-focal
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] HRHVJPFKCqE: Downloading webpage
[youtube] HRHVJPFKCqE: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 1966, in _real_extract
    yt_initial_data['contents']['twoColumnWatchNextResults']['conversationBar']['liveChatRenderer']['continuations'][0]['reloadContinuationData']['continuation']
KeyError: u'conversationBar'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dlc/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/youtube.py", line 2066, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dlc/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
```

## Description

Im simply trying to download a youtube video. Every video that I try including the one mentioned above returns with the stated error. Some other options work like --write-sub or --list-formats but download of the video fails. I had youtube-dl previously installed. Is there some cache I need to clear or is the issue something else? Thank you very much for your help!

**Comment by ChoiYun** [comment]
It was fixed in the #35
