### ISSUE TITLE
ERROR: Unable to extract JS player URL

### ISSUE THREAD

**Issue by gtaswin** [blackjack4494/yt-dlc#64]
When downloading the video getting this error,

ERROR: C0DPdy98e4c: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 1865, in _real_extract
    raise ExtractorError(
youtube_dlc.utils.ExtractorError: C0DPdy98e4c: YouTube said: Unable to extract video data

After retry..no error.
This issue happening randomly.

**Comment by gtaswin** [comment]
Already opened here https://github.com/blackjack4494/yt-dlc/issues/56
