### ISSUE TITLE
Unable to extract

### ISSUE THREAD

**Issue by gtaswin** [blackjack4494/yt-dlc#83]
Always getting error when downloading this video, https://www.youtube.com/watch?v=fRclAZ7h3sY

ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/extractor/youtube.py", line 2065, in _real_extract
    jsplayer_url_json = self._search_regex(
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dlc.utils.RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

**Comment by userlip** [comment]
Update to latest version
https://github.com/blackjack4494/yt-dlc/releases/tag/2020.10.31

**Comment by userlip** [comment]
And use the issue template next time please

**Comment by Alexis-Commits** [comment]
At source code (zip) version.py I see :  __version__ = '2020.10.25'
Are you sure that is updated?

**Comment by gtaswin** [comment]
After updated. Getting this error,

ERROR: Unable to download webpage: IncompleteRead(34987 bytes read) (caused by IncompleteRead(34987 bytes read)); please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; see  https://github.com/blackjack4494/yt-dlc  on how to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/YoutubeDL.py", line 2316, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.8/site-packages/youtube_dlc/utils.py", line 2626, in http_response
    content = resp.read()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 465, in read
    return self._readall_chunked()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 579, in _readall_chunked
    raise IncompleteRead(b''.join(value))
