### ISSUE TITLE
MKV Merging breaks when trying to download YouTube video with live chat replay (--all-subs)

### ISSUE THREAD

**Issue by etlam5123** [blackjack4494/yt-dlc#84]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
.\youtube-dlc.exe --embed-subs --all-subs -v https://www.youtube.com/watch?v=i520aRuZXLo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--embed-subs', '--all-subs', '-v', 'https://www.youtube.com/watch?v=i520aRuZXLo']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg n4.3.1-22-gc464b5c205, ffprobe n4.3.1-22-gc464b5c205
[debug] Proxy map: {}
[youtube] i520aRuZXLo: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[info] Writing video subtitles to: Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.live_chat.json
[debug] Invoking downloader on None
[download] Sleeping 0 seconds...
[youtube_live_chat_replay] Downloading live chat
[youtube_live_chat_replay] Total fragments: unknown (live)
[download] Destination: Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.live_chat.json
[download] 100% of 5.36MiB in 00:29
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://r6---sn-5goeen76.googlevideo.com/videoplayback?expire=1604183707&ei=O5KdX_rHAcWCpASmv4zQCw&ip=95.217.XXX.XXX&id=o-AATOAyOL7nIgZdjIEEc3zVBrKTkEvpqQ7nL8AllK7Gdu&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=Gw&mm=31%2C26&mn=sn-5goeen76%2Csn-i5heen7z&ms=au%2Conr&mv=m&mvi=6&pl=21&initcwndbps=765000&vprv=1&mime=video%2Fmp4&gir=yes&clen=216163200&dur=1666.320&lmt=1557495174182653&mt=1604161964&fvip=4&keepalive=yes&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKTQMNIVt4wEo6pCxbn9rGUPyhvyci6ad-agOh8toT57AiEAlNkuMj4KYqY0U6-dOUXDmeTnvppWLNCuw8kwVYzWGI4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMdE9atujqhA8ddKJIvr6LhQpHSoZ2zBZXW2tSiWBOz_AiEA6xLfp-LodcbDM9OkubMBw8rBMu9x-a5nOjgUztkUzfo%3D&ratebypass=yes'
[download] Destination: Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.f137.mp4
[download] 100% of 206.15MiB in 00:06
[debug] Invoking downloader on 'https://r6---sn-5goeen76.googlevideo.com/videoplayback?expire=1604183707&ei=O5KdX_rHAcWCpASmv4zQCw&ip=95.217.XXX.XXX&id=o-AATOAyOL7nIgZdjIEEc3zVBrKTkEvpqQ7nL8AllK7Gdu&itag=251&source=youtube&requiressl=yes&mh=Gw&mm=31%2C26&mn=sn-5goeen76%2Csn-i5heen7z&ms=au%2Conr&mv=m&mvi=6&pl=21&initcwndbps=765000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=27953977&dur=1666.341&lmt=1557494207316064&mt=1604161964&fvip=4&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgTBmjFoPMP580q2sUsEeP5SOtv0fYp9uWwE_GJTnrftMCIDGpUewFebYUrU0jkHJ7orHkSjeXIdy5sK0OCi16Khku&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMdE9atujqhA8ddKJIvr6LhQpHSoZ2zBZXW2tSiWBOz_AiEA6xLfp-LodcbDM9OkubMBw8rBMu9x-a5nOjgUztkUzfo%3D&ratebypass=yes'
[download] Destination: Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.f251.webm
[download] 100% of 26.66MiB in 00:00
[ffmpeg] Merging formats into "Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.f137.mp4" -i "file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.temp.mkv"
Deleting original file Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.f137.mp4 (pass -k to keep)
Deleting original file Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.f251.webm (pass -k to keep)
[ffmpeg] Embedding subtitles in 'Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.mkv'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.mkv" -i "file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.live_chat.json" -map 0 -c copy -map "-0:s" -map "-0:d" -map "1:0" "-metadata:s:s:0" "language=lim" "file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.temp.mkv"
ERROR: file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.live_chat.json: Invalid data found when processing input
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 2150, in post_process
  File "youtube_dlc\postprocessor\ffmpeg.py", line 447, in run
  File "youtube_dlc\postprocessor\ffmpeg.py", line 235, in run_ffmpeg_multiple_files
youtube_dlc.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Jeff The Killer - Creepypasta _ Sundance Rejects-i520aRuZXLo.live_chat.json: Invalid data found when processing input
```

## Description

When trying to download a video from YouTube that had a live chat, youtube-dlc downloads that live chat as a json file and tries to merge it into the mkv file. However ffmpeg doesn't seem to like that.

**Comment by etec-masterofsynapse** [comment]
Just out of interest, did you try the same video without the "--embed-subs" option?
I suspect there is a bug that lets youtube-dlc think that it should merge the json of the live chat as a subtitle file into the mkv, which obvs doesnt work.
Because you can see in the log file that the live chat is downloaded as a "subtitle file".

**Comment by etlam5123** [comment]
Indeed when I do not use "--embed-subs", youtube-dlc does not try to merge it. Strange why the chat is considered as subtitle.

**Comment by etec-masterofsynapse** [comment]
> Indeed when I do not use "--embed-subs", youtube-dlc does not try to merge it. Strange why the chat is considered as subtitle.

Great to hear it works that way.
I suspect that during the scripting of the YouTube "engine" the devs took the easy way and considered every addon file to a YT video a subtitle, not accounting for downloadable live chat replays. There should be a distinction between the .vtt or .srt files, that are mergeable, and the .json which are not.

**Comment by pukkandan** [comment]
The live chat downloading is a patch originally implemented by @siikamiika 
The feature is implemented by creating a subtitle extractor `YoutubeLiveChatReplayFD` and redirecting `--sub-lang live_chat_replay` to it. This is why `--embed-subs` tries to embed the live chat into the video file.
