### ISSUE TITLE
Cookies causing Error

### ISSUE THREAD

**Issue by GhostGuy9** [blackjack4494/yt-dlc#87]
- [ X] I've verified that I'm running youtube-dlc version **2020.10.31**
- [X ] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X ] I've searched the bugtracker for similar bug reports including closed ones
- [X ] I've read bugs section in FAQ

## Verbose log

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', 'cookies.txt', '-v', 'https://www.youtube.com/watch?v=7takIh1nK0s']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.10.31
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7takIh1nK0s: Downloading webpage
[youtube] 7takIh1nK0s: Downloading embed webpage
ERROR: 7takIh1nK0s: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 1903, in _real_extract
youtube_dlc.utils.ExtractorError: 7takIh1nK0s: YouTube said: Unable to extract video data

## Description

I tested it on many videos but it seems that it only works when I don't have cookies. I need cookies to download a different video but tested it on a non-age limit video to insure its not because of age restriction.

**Comment by blackjack4494** [comment]
It's super hard to test and fix this. Most of the times it works for me and only sometimes it doesn't.

**Comment by JesusIslam** [comment]
Got similar problem trying to download membership only video:

```
 $ youtube-dl --verbose -f "[height=720]" -o test.mp4 --cookies ./sample_data/cookies.txt https://youtube.com/watch?v=somevideo
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'-f', u'[height=720]', u'-o', u'test.mp4', u'--cookies', u'./sample_data/cookies.txt', u'https://youtube.com/watch?v=somevideo']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.10.26
[debug] Python version 2.7.10 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 36PavafFw7U: Downloading webpage
[youtube] 36PavafFw7U: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dlc/YoutubeDL.py", line 830, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dlc/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dlc/extractor/youtube.py", line 2066, in _real_extract
    ASSETS_RE, embed_webpage, 'JS player URL')
  File "/usr/local/bin/youtube-dl/youtube_dlc/extractor/common.py", line 1010, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dlc -U  to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.

```

**Comment by ALXMRW** [comment]
I've been dealing with this exact issue (more info at #37) since October 20th and it still persists even with 2020.10.31. Hopefully something can eventually be figured out.

**Comment by nalllen** [comment]
Same problem here using private playlist. "cookies"

Traceback (most recent call last):
  File "youtube_dlc\YoutubeDL.py", line 830, in extract_info
  File "youtube_dlc\extractor\common.py", line 532, in extract
  File "youtube_dlc\extractor\youtube.py", line 1962, in _real_extract
youtube_dlc.utils.ExtractorError: youtube-dlc: YouTube said: Unable to extract video data

**Comment by blackjack4494** [comment]
There are some videos where yt-dlc still have troubles to extract video id or data. However I never experienced any problems on my side. That's why it's also hard to try to fix it.

**Comment by GhostGuy9** [comment]
New Update, 2020.11.07, fixes problem with cookies. Tested it and works perfectly.

**Comment by someziggyman** [comment]
These links are failing to download with cookies:
https://www.youtube.com/watch?v=7takIh1nK0s
https://www.youtube.com/watch?v=XgnwCQzjau8

Without cookies getting _ERROR: Video is age restricted and only playable on Youtube. Requires cookies!_  which is expected behaviour. 

Log below:
./dlctest -v -F --cookies cooktest.txt https://www.youtube.com/watch?v=7takIh1nK0s
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'--cookies', u'cooktest.txt', u'https://www.youtube.com/watch?v=7takIh1nK0s']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dlc version 2020.11.11-2
[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7takIh1nK0s: Downloading webpage
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./dlctest/__main__.py", line 19, in <module>
  File "./dlctest/youtube_dlc/__init__.py", line 487, in main
  File "./dlctest/youtube_dlc/__init__.py", line 477, in _real_main
  File "./dlctest/youtube_dlc/YoutubeDL.py", line 2104, in download
  File "./dlctest/youtube_dlc/YoutubeDL.py", line 830, in extract_info
  File "./dlctest/youtube_dlc/extractor/common.py", line 532, in extract
  File "./dlctest/youtube_dlc/extractor/youtube.py", line 1865, in _real_extract
  File "./dlctest/youtube_dlc/extractor/common.py", line 2866, in _get_cookies
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'
